### ISSUE TITLE
Will Hugectr add more support for tensorflow model transfering

### ISSUE THREAD

**Issue by BookChan** [NVIDIA-Merlin/HugeCTR#16]
Currently,  there are only one tutorial  about transfering hugectr model to tensorflow model: https://github.com/NVIDIA/HugeCTR/tree/master/tutorial/dump_to_tf .   And the tutorial code  is not well  architectured , and seems to be a specific example , but not a common reuse modular.
My question is: what's  the plan  hugectr team to  develop a common python moduar, which should have the following behaviors:

- Input:   hugectr  model config file path,   tensorflow output path
- Output:   tensorflow model  under  tensorflow output path

**Comment by eric-haibin-lin** [comment]
Same question - any update?

**Comment by dibyadip-das** [comment]
same question

**Comment by zehuanw** [comment]
Hi @BookChan @eric-haibin-lin @dibyadip-das , thank you for your feedback and sorry for late reply! We have supported ONNX convertor in HugeCTR https://nvidia-merlin.github.io/HugeCTR/master/hugectr_core_features.html#hugectr-to-onnx-converter. You may want to try to convert ONNX model to TF as your second step. https://stackoverflow.com/questions/58834684/how-could-i-convert-onnx-model-to-tensorflow-saved-model. I'm closing this issue, but if my answer doesn't solve your problem please reopen it.
