### ISSUE TITLE
Can hugectr add predict command?

### ISSUE THREAD

**Issue by BookChan** [NVIDIA-Merlin/HugeCTR#17]
Currently , the hugectr main process supports: [--train] [--help] [--version]  . However, it's a common scenario that  when training is done  we predict the test data and print the result on the screen  which can redirect to file.

With the predict result, we can :
1. Comparing the hugectr predict result with the transferred tensorflow model's ,  to make sure the transfering process is correct.
2. Use the result to calculate other metric , like auc , precision, etc.
3. Do batch prediction.

Can hugectr add predict command?  

- huge_ctr --predict  model_config.json   test_file_list.txt

**Comment by bashimao** [comment]
Old issue that can be closed.

HugeCTR has added such an interface now. For production-system inference tasks, we now also provide a plugin for NVIDIA Triton. You can find the [HugeCTR NVIDIA Triton Backend](https://github.com/triton-inference-server/hugectr_backend) [here](https://github.com/triton-inference-server/hugectr_backend).
