### ISSUE TITLE
TensorRT support in Inference

### ISSUE THREAD

**Issue by zehuanw** [NVIDIA-Merlin/HugeCTR#171]
Just put a Placeholder here.

**Comment by JacoCheung** [comment]
Already planned.

**Comment by KingsleyLiu-NV** [comment]
TensorRT inference for HugeCTR trained model is supported in 23.02 release. See this demo notebook: https://nvidia-merlin.github.io/HugeCTR/main/hps_trt/notebooks/demo_for_hugectr_trained_model.html
