### ISSUE TITLE
[Question] about Quick Start

### ISSUE THREAD

**Issue by ucasiggcas** [NVIDIA-Merlin/HugeCTR#176]
hi,dear
If  I do not have root,so I can't use docker, and I just clone the rp,then how to start?
could you pls help me ?
thx

**Comment by zehuanw** [comment]
Hi @ucasiggcas , sorry for the late reply. You may want to install every dependencies according to Merlin dockerfile yourself: https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/dockerfile.ctr

I'm closing this issue, but please reopen it if it doesn't solve your problem. Thanks!
