### ISSUE TITLE
[Requirement] Summary for docker image upgrade

### ISSUE THREAD

**Issue by XiaoleiShi-NV** [NVIDIA-Merlin/HugeCTR#177]
We are trying to collect the docker image related feature/issue/idea for making it fully-functional/stable/easy to use.

Summary doc: https://docs.google.com/document/d/1ZlG_DV-sOWah9DVVz8v31ySQY9Q6aopWmA4kjnNC7tg/edit?usp=sharing

**Comment by bashimao** [comment]
Closing because superseded by Merlin image upgrade.
