### ISSUE TITLE
[Requirement] Requirements for NGC docker image

### ISSUE THREAD

**Issue by XiaoleiShi-NV** [NVIDIA-Merlin/HugeCTR#178]
For the user's convenience, we should copy some necessary but minimal job scripts and corresponding datasets to the NGC docker image.

**Comment by bashimao** [comment]
Thanks for your bringing this to our attention.

Unfortunately, legal constraints prevent us from including datasets directly in our images.

Notebooks and scripts have been revised accordingly in [v3.4](https://github.com/NVIDIA-Merlin/HugeCTR/releases/tag/v3.4). If you still find issues, please do not hesitate to re-open this or create a new issue.
