### ISSUE TITLE
[Requirement] Install version specified dependencies for CUDF in dev.Dockerfile

### ISSUE THREAD

**Issue by XiaoleiShi-NV** [NVIDIA-Merlin/HugeCTR#179]
Currently we don't specify the version for dependencies of CUDF in dev.Dockerfile, which may be at risk when one of them updated by Ubuntu.

**Comment by XiaoleiShi-NV** [comment]
```
apt update && apt install -y libarrow-dev libarrow-cuda-dev && \
dpkg -r --force-depends libnvidia-compute-450-server
```

**Comment by EmmaQiaoCh** [comment]
We are now using cudf installed from upstream merlin-base image.
