### ISSUE TITLE
request automatic export of hugectr models to tensorflow.

### ISSUE THREAD

**Issue by harsha-sharechat-account** [NVIDIA-Merlin/HugeCTR#180]
1.can you add support to tensorflow export from the hugectr checkpoints directly without having to build the computation graph manually.
2. Also can you provide some examples for building the computation graph for dcn , dlrm,wdl,deepfm respectively based on the standard config files.

**Comment by zehuanw** [comment]
Hi @harsha-sharechat-account sorry for late reply. 
> can you add support to tensorflow export from the hugectr checkpoints directly without having to build the computation graph manually.

We have supported ONNX support in HugeCTR. Please refer to https://nvidia-merlin.github.io/HugeCTR/master/hugectr_core_features.html#hugectr-to-onnx-converter
and https://stackoverflow.com/questions/58834684/how-could-i-convert-onnx-model-to-tensorflow-saved-model

I'm closing this issue, but if my answer doesn't solve your problem please reopen it.
