### ISSUE TITLE
[Requirement] Supporting libsvm in input dataset

### ISSUE THREAD

**Issue by zehuanw** [NVIDIA-Merlin/HugeCTR#188]
**Is your feature request related to a problem? Please describe.**
libsvm is a kind of commonly used format. The biggest advantage is that it's readable by human beings. [MB]

**Describe the solution you'd like**
Supporting libsvm in HugeCTR data reader

**Comment by JacoCheung** [comment]
This feature is at low priority. And we're understaffed.
