### ISSUE TITLE
grammar for input json files

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA-Merlin/HugeCTR#19]
Would you please let me know where can I find the grammer for input json files?

**Comment by zehuanw** [comment]
Thank you for your question! Please refer to our [user guide](https://github.com/NVIDIA/HugeCTR/blob/master/docs/hugectr_user_guide.md):

**Comment by ethem-kinginthenorth** [comment]
@zehuanw . thanks. the link you provided has just a couple of examples. What I am interested in is a grammar file that defines the input json file. For example (just making up):
an input file consists of solver + optimizer + layers (you can also give me something like input = ( solver, optimizer, layers)
layers = ( layer1 | layer2 | layer3 .... | layern )+ ...... )
a layer can be among these: layer1, layer2, layer3
parameters of layer1 is [this, that, and that one as well]
...
parameters of layern is [that, thatone, thatoneaswell]

I hope this makes sense. 

Thanks

**Comment by zehuanw** [comment]
Added labels and milestone. This requirement will be addressed in our next release. THX!

**Comment by ethem-kinginthenorth** [comment]
just to give you and idea why I am interested in this: https://github.com/ethem-kinginthenorth/HugeCTRpy

**Comment by bashimao** [comment]
Closing. Starting from v3 HugeCTR provides a Python API, that has matured over the past months and can now be considered as stable.
