### ISSUE TITLE
Synthetic Data for HugeCTR/samples/dlrm[Question]

### ISSUE THREAD

**Issue by initzhang** [NVIDIA-Merlin/HugeCTR#193]
The `data_generator` do a great job for quick benchmarking in `HugeCTR/samples/dcn`, however it seems unavailable in `HugeCTR/samples/dlrm` 

> HugeCTR/samples/dlrm/README.md doesn't mention the `data_generator` method, and the result of `data_generator dlrm_fp16_16k.json` can not be correctly feed to `huge_ctr --train dlrm_fp16_16k.json`, the error message is " [HCDEBUG][ERROR] Runtime error: Localized_slot_sparse_embedding_one_hot cannot support multi-node currently."
>  
> **To Reproduce**
> 1. docker pull the latest hugectr:v2.3  (2020.12.23)
> 2. cd HugeCTR/samples/dlrm
> 3. data_generator dlrm_fp16_16k.json
> 4. huge_ctr --train dlrm_fp16_16k.json

So I am wondering is it impossible to use data_generator in sample/dlrm?

**Comment by bashimao** [comment]
@KingsleyLiu-NV I believe you used the data_generator for benchmarking DLRM recently. Didn't you? Is that code included in the public release?

**Comment by KingsleyLiu-NV** [comment]
> @KingsleyLiu-NV I believe you used the data_generator for benchmarking DLRM recently. Didn't you? Is that code included in the public release?

@bashimao 
This is not data generation issue. As the error message indicates, there is some restrictions for `LocalizedSlotSparseEmbeddingOneHot`.
Here is a script to generate Raw synthetic dataset and train DLRM model: https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/tools/data_generator/dlrm_raw_generate_train.py. You can run it on systems that enable peer-to-peer access like DGX-2.

**Comment by zehuanw** [comment]
Hi @initzhang , thank you for your feedback! We'd like to close this issue, please reopen it if @KingsleyLiu-NV 's reply doesn't solve your problem.
