### ISSUE TITLE
[Question] Can libembedding_plugin.so work with Tensorflow 1.15?

### ISSUE THREAD

**Issue by serser** [NVIDIA-Merlin/HugeCTR#195]
I can load ` libembedding_plugin.so` in tf1.15, but `OP_LIST` is empty. To reproduce,

```
from tensorflow.python.framework import load_library
embedding_plugin_ops = load_library.load_op_library(path)
print(embedding_plugin_ops.OP_LIST)
```

Or is it possible for me to recompile a .so for tf1.15?

**Comment by serser** [comment]
I see that the default tf in the [container](https://ngc.nvidia.com/catalog/containers/nvidia:hugectr) is `2.5.0-dev20201120`, how is was installed? It doesn't seem to be in the [Dockerfile](https://github.com/NVIDIA/HugeCTR/blob/master/tools/dockerfiles/build.Dockerfile).

**Comment by Jianbing-D** [comment]
Currently, we only tested `embedding_plugin` with TF 2.x. To use it with TF 1.x, some `#include` headers should be modified to fit TF 1.x, and link with TF 1.x's dynamic libs.

In terms of the version of installed TF, it is installed by this [instruction](https://github.com/NVIDIA/HugeCTR/blob/master/tools/dockerfiles/build.Dockerfile#L40). 

We will add TF 1.x support to `embedding_plugin` in near future, please looking forward to it.

**Comment by zehuanw** [comment]
Hi @serser , Thank you for your feedback! TF 1.x has been supported in TF 1.15. https://nvidia-merlin.github.io/HugeCTR/sparse_operation_kit/master/get_started/get_started.html#tensorflow-1-15

We'd like to close this issue. Please open a new issue if you face more problems.
