### ISSUE TITLE
nccl error when using 4 v100 gpus and 38081921 as vocab size where dim=8

### ISSUE THREAD

**Issue by harsha-sharechat-account** [NVIDIA-Merlin/HugeCTR#197]
<img width="1680" alt="Screenshot 2020-12-28 at 9 25 05 PM" src="https://user-images.githubusercontent.com/56540081/103226951-40033f80-4953-11eb-83a2-1e7dad9a459a.png">
I am facing the error when using 4 gpus with each having a max vocab size of 9520481
but when I use only 2 gpu with each having a max vocab size of 9520481*2  (with all other params constant)i am not getting this error

**Comment by zehuanw** [comment]
This issue was created one year ago and HugeCTR have been updated from v2.3 to v3.3. I'd like to close it first. If you still face the same problem in our latest release we can open a new one. Thank you for your feedback!
