### ISSUE TITLE
Can Hugectr supports Sequence Model?

### ISSUE THREAD

**Issue by BookChan** [NVIDIA-Merlin/HugeCTR#20]
Currently the embedding layer, supports  mean or sum pooling for the variable length. In the deep learning word, using LSTM 、 Attention,  is normal.  For example , [DIN](https://arxiv.org/abs/1706.06978)  model uses  attention layer to merge  user behavior sequence.   

Can Hugectr supports Sequence Model,  such as  LSTM 、 GRU  、 Attention ，etc?

**Comment by zehuanw** [comment]
Thank you for your question. We are going to support DIEN in v3.0, DIN support will be discussed and reply to you.

**Comment by zehuanw** [comment]
Hi @BookChan , DIN has been supported on https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/samples/din. Thank you for your feedback!
