### ISSUE TITLE
[Question]how to config deepfm.json or wdl.json to support sequence feautre

### ISSUE THREAD

**Issue by zhoujiang2013** [NVIDIA-Merlin/HugeCTR#202]
sequence feature: i want to use behavior seq in model, such as user0's click sequence hist = [item0, item1 ,item2] .I want to use fixedLen = 8, and  then use sum pooling to combine during the sequence embedding.
how to config deepfm.json or wdl.json to support sequence feature.
Does it work in version v2.3.
Look forward to your reply.

**Comment by zehuanw** [comment]
Hi @zhoujiang2013 , thank you for your support! 

By using DistributedSlotEmbedding, all the slots will be distributed across GPU/Nodes. In your case (hist = [item0, item1 ,item2]), you can just allocate a three slot embedding, 

This feature should be workable in current v2.3 release and we plan to support DIEN / DIN in the near future.

**Comment by zhoujiang2013** [comment]
two more questions：
1. is use three slot embedding ,how can i make sure those itemId use the same embedding. 
2. if the seq is 16 and also use category seq hist_cate = [cate0, cate1,cate2,..],   the slots num is so large. for online predict it also lead to much more engineering task.

**Comment by zehuanw** [comment]
1. They will use the same embedding. Actually all the slots in the same embedding layer sharing the same space. 
2. Hmm, could you please elaborate more? For example `slot_num = 16`, what you need to do is only send 16 elements into this embedding as input. The only change is input dimension. @zhoujiang2013

**Comment by zehuanw** [comment]
In the recent releases, we have moved to [python API](https://nvidia-merlin.github.io/HugeCTR/master/api/index.html). I'd like to close this issue, if you face more problems, we will appreciate if you can open a new issue. Thank you for your feedback again!
