### ISSUE TITLE
Tutorials Are Not Sufficient and Confusing[BUG]

### ISSUE THREAD

**Issue by darien-schettler** [NVIDIA-Merlin/HugeCTR#203]
**Describe the bug**
The tutorial notebooks provided for HugeCTR are borderline incomprehensible. 
  - Please endeavour to make tutorials/notebooks that explain what is being done and why it is being done in more detail.
  - Please avoid using overly complicated steps/functions with next to no comments describing the functionality
  - Please try and use NVTabular and CuDF in the notebooks as HugeCTR is a critical component in Merlin

**To Reproduce**
Steps to reproduce the behaviour:
1. Open [this notebook](https://github.com/NVIDIA/HugeCTR/blob/master/notebooks/movie-lens-example.ipynb
) and read through it.
2. Now try and change/customize things in a meaningful way.
3. Struggle

**Expected Behaviour**
I expect the documentation, tutorials, notebooks, etc. to be clear and helpful. I expect them to help me develop an understanding that will allow me to pivot and use this tool for other datasets with various types of columns and datatypes.

**Additional context**
I am submitting this as a bug because I legitimately think it is hurting the functionality of the software. HugeCTR is a powerful tool, but if it is cumbersome and difficult to figure out how to use it, that's a problem. Please understand I'm not trying to be difficult or rude, I want to be able to advocate for this software (Merlin in general), but poor documentation/tutorials/notebooks is making that hard.

Thank you in advance.

**Comment by zehuanw** [comment]
Thank you for your valuable suggestions and support! We are addressing your issue in this release and you will see the changes soon (in about one month). 
Documents to be added/updated:
- Layer book  
- Python API book
- Updated Notebooks with more introductions / links to Python API book.
- Configure file setup manual
- Changelog
