### ISSUE TITLE
[BUG] HugeCTR doc link is broken

### ISSUE THREAD

**Issue by efrats** [NVIDIA-Merlin/HugeCTR#204]
**Describe the bug**
under HugeCTR the link embedded to the user guide is broken

For additional information, see the HugeCTR User Guide.
**To Reproduce**
1. How to build including `docker pull & docker run` commands
2. How to run including the JSON config file used

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu xx.yy]
 - Graphic card: [e.g. a single NVIDIA V100 or NVIDIA DGX A100]
 - CUDA version: [e.g. CUDA 11.x]
 - Docker image

**Additional context**

**Comment by zehuanw** [comment]
Thank you for your feedback! We just updated our document. Please check if it's fixed for you.
