### ISSUE TITLE
[Qustion] Cant build; no function named "set_evaluate_stage" in "session"

### ISSUE THREAD

**Issue by dare0021** [NVIDIA-Merlin/HugeCTR#212]
When trying to build from a cloned copy, build fails with the message

```
/mnt/HugeCTR/HugeCTR/src/main.cpp: In function 'void train(std::string)':
/mnt/HugeCTR/HugeCTR/src/main.cpp:294:25: error: 'using element_type = class HugeCTR::Session' {aka 'class HugeCTR::Session'} has no member named 'set_evaluate_stage'
  294 |       session_instance->set_evaluate_stage();
      |                         ^~~~~~~~~~~~~~~~~~~
```
Looking in the HugeCTR/src/session.cpp file shows there is no such function, and the repo history shows the file has never had the function
Yet the last HugeCTR/src/main.cpp file without the function call was for 2.1
Since it seems unlikely this has been a bug for so long, I file this as a question.

The build options were
```
cmake -DSM=70 -DNCCL_A2A=ON ..
make -j 20
```

on a V100 DGX running Ubuntu

Build was tried on the NGC container for merlin, the same one mentioned in HugeCTR docs
`source activate merlin `was called before building

**Comment by zehuanw** [comment]
Hi @dare0021 , sorry for the late reply. We have a [contributing to HugeCTR doc](https://nvidia-merlin.github.io/HugeCTR/master/hugectr_contributor_guide.html) now. Would you like to have a try? Please reopen this issue if it doesn't solve your problem. Thanks!
