### ISSUE TITLE
[BUG] Missing keys in model file

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA-Merlin/HugeCTR#218]
**Describe the bug**
Upon reading the embedding table from a saved model (trained using parquet data), the number of keys is smaller than the number of expected entries (i.e. the number of unique categories in the training data).

**To Reproduce**

From the Merlin training v0.5 docker image, run the following notebooks:

1. To train model
https://github.com/vinhngx/NVTabular/blob/hugectr-missing-keys/examples/getting-started-movielens/inference-HugeCTR/advanced-movie-lens-feature-engineering-multiGPU-20-80-split.ipynb

2. To read item embeddings back:
https://github.com/vinhngx/NVTabular/blob/hugectr-missing-keys/examples/getting-started-movielens/inference-HugeCTR/nearest_neighbor_query.ipynb

**Expected behavior**
```
slot_size_array=[
137,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 162542,
 56586]
```
vs. actual number of keys for each slot:

```
136
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
162541
52487
```
Note that NVTab reserves an extra category (for missing data) which does not appear in the training data, hence the difference of 1 in every category.

Notice that ~4k of movie embeddings are missing from the model.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu xx.yy]
 - Graphic card: [e.g. a single NVIDIA V100 or NVIDIA DGX A100]
 - CUDA version: [e.g. CUDA 11.x]
 - Docker image

**Additional context**

**Comment by KingsleyLiu-NV** [comment]
Hi @vinhngx 
This issue was caused by the wrong behavior of the Parquet data reader and has been fixed since v3.1,
