### ISSUE TITLE
v2.2  build error

### ISSUE THREAD

**Issue by BookChan** [NVIDIA-Merlin/HugeCTR#22]
build v2.2 with command : mkdir build && cd build &&  cmake -DCMAKE_BUILD_TYPE=Release    -DNCCL_A2A=ON -DSM=70    ..  && make -j

got error:
[  3%] Building CUDA object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/layers/batch_norm_layer.cu.o                                                                       
nvcc fatal   : Value 'all-warnings' is not defined for option 'Werror'                                                                                                    
HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:134: recipe for target 'HugeCTR/src/CMakeFiles/huge_ctr_static.dir/layers/batch_norm_layer.cu.o' failed             
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/layers/batch_norm_layer.cu.o] Error 1                                                                            
CMakeFiles/Makefile2:124: recipe for target 'HugeCTR/src/CMakeFiles/huge_ctr_static.dir/all' failed                                                                       
make[1]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/all] Error 2                                                                                                     
Makefile:129: recipe for target 'all' failed                                                                                                                              
make: *** [all] Error 2   

and 

data/HugeCTR/test/utest/layers/multi_cross_layer_test.cpp:276:25: note: suggested alternative: 'compare_array_approx'
/data/HugeCTR/test/utest/layers/multi_cross_layer_test.cpp:276:7: error: expected primary-expression before '(' token
       ASSERT_TRUE(test::compare_array_approx_with_ratio<float>(

Solution:  
we fix the error by deleting some conf in CMakeLists.txt,
delete the  "--Werror  all-warnings"  and  test modular.

Does  the  v2.2   testing  use the dockerfile?

**Comment by zehuanw** [comment]
Thank you for your feedback, we are trying to reproduce this issue.

**Comment by weiyingcan** [comment]
> build v2.2 with command : mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DNCCL_A2A=ON -DSM=70 .. && make -j
> 
> got error:
> [ 3%] Building CUDA object HugeCTR/src/CMakeFiles/huge_ctr_static.dir/layers/batch_norm_layer.cu.o
> nvcc fatal : Value 'all-warnings' is not defined for option 'Werror'
> HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:134: recipe for target 'HugeCTR/src/CMakeFiles/huge_ctr_static.dir/layers/batch_norm_layer.cu.o' failed
> make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/layers/batch_norm_layer.cu.o] Error 1
> CMakeFiles/Makefile2:124: recipe for target 'HugeCTR/src/CMakeFiles/huge_ctr_static.dir/all' failed
> make[1]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> and
> 
> data/HugeCTR/test/utest/layers/multi_cross_layer_test.cpp:276:25: note: suggested alternative: 'compare_array_approx'
> /data/HugeCTR/test/utest/layers/multi_cross_layer_test.cpp:276:7: error: expected primary-expression before '(' token
> ASSERT_TRUE(test::compare_array_approx_with_ratio(
> 
> Solution:
> we fix the error by deleting some conf in CMakeLists.txt,
> delete the "--Werror all-warnings" and test modular.
> 
> Does the v2.2 testing use the dockerfile?

I have tried to reproduce your issue with dev.Dockerfile but not success. Since HugeCTR treats warning as error, if some modifications on source code brings the warnings, it leads to build error.
