### ISSUE TITLE
[Requirement] Can HugeCTR support embedding lookup with no pooling (e.g. flattened embedding vectors)

### ISSUE THREAD

**Issue by marsmiao** [NVIDIA-Merlin/HugeCTR#240]
**Is your feature request related to a problem? Please describe.**
Can HugeCTR support mlp-attention(quote: https://github.com/nicolay-r/mlp-attention) based on current api? Or if HugeCTR is able to support embedding lookup with no pooling as the title described.

**Describe the solution you'd like**
As far as I'm considered, there only be like add a sparse embedding which could output the flattened embedding vectors and the segment_id(which describe the CSR dense shape), and then the dense layer can use the embedding vectors to multiply a tensor (e.g. attention sparse weights tensor), then use the segment_id to pooling(combine).

**Comment by zehuanw** [comment]
Hi @marsmiao , thank you for your feedback!. For now, as a workaround, embedding lookup without pooling can be supported by configuring your embedding/data as one hot. Our pooling is only applied per slot, so if you configure as one hot you will expect no pooling. The limitation of this WAR is that the length of input record should be fixed (slot_num is specified when embedding is created).

Your feedback is valuable for us. We need some internal discussion on the requirement. If you can provide more information and help us to understand the importance of this requirement, it will help us to prioritize this feature.

**Comment by zehuanw** [comment]
Hi @marsmiao , Thank you for your feedback again! A new Embedding has been implemented with no pooling. Please find more details here: https://nvidia-merlin.github.io/HugeCTR/sparse_operation_kit/master/api/embeddings/dense/all2all.html

We are closing this issue. If my answer doesn't solve your problem please reopen it.
