### ISSUE TITLE
[Question] About gpu cache

### ISSUE THREAD

**Issue by ninawangwei** [NVIDIA-Merlin/HugeCTR#241]
I have two questions about gpu cache, any response will be appreciated.
1. Need I tune `warp_size` or `set_associativity` if we use `int8` as the value type.
2. I notice you de-duplicate the key id before looking up in gpu cache, would you share some results about how much acceleration can it bring?

Thanks.

**Comment by HWZealot** [comment]
Hi,
1. For value type(embedding vector type), it doesn't affect the way how a key is been searched in the cache. So it doesn't affect the choice for these hyper-parameters(i.e. `warp_size` or `set_associativity`).
2. De-duplication is important to current implementation. In current design, to enable thread-safety , any keys that are mapped to the same cache set will be operated(search or insert) serially while keys that are mapped to different cache sets will be operated in parallel. We implemented a random hash function to map keys to different cache set, so if two keys are different, they are very unlikely to be mapped to the same cache set. However, for duplicated keys, they will always been mapped to the same cache set, thus if you have 2 duplicated keys, they will be searched serially and cost 2x time for retrieving the same embedding vector(which is also useless even if the searching process can happen in parallel). So, de-duplication, which works like compression here, is important to the performance of gpu cache.

Thanks.
