### ISSUE TITLE
Invalid value for capacity_in_set

### ISSUE THREAD

**Issue by gayatrishandar** [NVIDIA-Merlin/HugeCTR#247]
i am getting an error when i execute this line:
`embedding_cache=CreateEmbeddingCache(parameter_server,0,True,0.2,inf_json,"DLRM",True)`
where `inf_json` is the config file for inference.

The error is:
[HCDEBUG][ERROR] Runtime error: Error: Invalid value for capacity_in_set /var/tmp/HugeCTR/HugeCTR/src/inference/gpu_cache/nv_gpu_cache.cu

Looking into the code it looks like 0 is an invalid value for `capacity_in_set`, but the `CreateEmbeddingCache` doesn't seem to take `capacity_in_set` in its constructor, so i'm unsure how to configure this value.

Thanks in advance! 

**Note**: Before filing an issue, you may want to check out [our compiled Q&A list](https://github.com/NVIDIA/HugeCTR/blob/master/docs/QAList.md) first.

**Comment by zehuanw** [comment]
Hi @gayatrishandar , we are closing this issue. If @yingcanw 's reply doesn't solve your problem, please reopen it. Thanks!
