### ISSUE TITLE
[BUG] Timestamp after evaluation is off during model fit

### ISSUE THREAD

**Issue by paulhendricks** [NVIDIA-Merlin/HugeCTR#257]
**Describe the bug**

It appears HugeCTR combines the time taken after a set of iterations with the time taken to do an evaluation and reports that - this results in timestamps of 90s or 70s, etc.

![Screen Shot 2021-10-20 at 1 50 50 PM](https://user-images.githubusercontent.com/7489752/138145233-79793ca8-753d-4d51-a0ba-63af9db8b9b6.png)

**To Reproduce**
Run any HugeCTR model.

**Expected behavior**
Perhaps timestamp after the last training iteration. Then a timestamp for evaluation finish. Then timestamp for next training iteration.

**Screenshots**
See above.

**Environment (please complete the following information):**

nvcr.io/nvidia/merlin/merlin-training:21.09

**Additional context**

**Comment by bashimao** [comment]
@paulhendricks thanks for bringing this to our attention. Despite our best efforts, we were unsuccessful to provoke this issue in our test environment. However, we found a potential race condition in the logging code that could cause faulty rendering of timestamps. A fix is included in the [v3.4](https://github.com/NVIDIA-Merlin/HugeCTR/releases/tag/v3.4) release of HugeCTR.

Closing this issue for now. If you still experience this or a likewise issue with [HugeCTR v3.4](https://github.com/NVIDIA-Merlin/HugeCTR/releases/tag/v3.4) or later, please do not hesitate to re-open this or create a new issue.
