### ISSUE TITLE
AttributeError: 'WorkflowNode' object has no attribute 'columns'[Question]

### ISSUE THREAD

**Issue by ng-fukgin** [NVIDIA-Merlin/HugeCTR#265]
When i run the follow code from  [ecommerce-example.ipynb](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/notebooks/ecommerce-example.ipynb)
```
dict_dtypes = {}
for col in cat_feats.columns:
    dict_dtypes[col] = np.int64
for col in cont_feats.columns:
    dict_dtypes[col] = np.float32

dict_dtypes['target'] = np.float32
```

there are the error 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_368/3247637301.py in <module>
      1 dict_dtypes = {}
----> 2 for col in cat_feats.columns:
      3     dict_dtypes[col] = np.int64
      4 for col in cont_feats.columns:
      5     dict_dtypes[col] = np.float32

AttributeError: 'WorkflowNode' object has no attribute 'columns'
```

**Comment by ng-fukgin** [comment]
How can i do ?
i launch the container in interactive modeby running this command:
`docker run --runtime=nvidia --rm -it --cap-add SYS_NICE  -v $(pwd):/hugectr -w /hugectr -p 8888:8888 nvcr.io/nvidia/merlin/merlin-training:21.11
`

**Comment by vinhngx** [comment]
hi @ng-fukgin, thanks for reporting this. This was due to some NVTabular API breaking changes.
We have now provided a fix. Could you please try again and let us know.
Thanks.

**Comment by ng-fukgin** [comment]
> hi @ng-fukgin, thanks for reporting this. This was due to some NVTabular API breaking changes. We have now provided a fix. Could you please try again and let us know. Thanks.

Now enerything is Okay,Thanks you very much!!
