### ISSUE TITLE
[Requirement] sok installation via pypi

### ISSUE THREAD

**Issue by nrailgun** [NVIDIA-Merlin/HugeCTR#266]
Currently sok shared library must be compiled and installed as root, while the python scripts must be manually copied (Am I right?). That's inconvenient in production environment.

Hope sok could provide the ability to build wheel, which makes things a little easier.

Thank you very much.

**Comment by zehuanw** [comment]
Hi @nrailgun , thank you for your suggestions! They are very valuable for us to improve our user experience.

> Currently sok shared library must be compiled and installed as root,
As we have provided NGC container for example in this release: "nvcr.io/nvidia/merlin/merlin-tensorflow-training:21.11", 
- do you think it's sufficient or you need some solution like conda install or pip install? 
- If installing from source code is acceptable to you, how does install as root make things difficult?

> while the python scripts must be manually copied.
Which python scripts you want to copy?

**Comment by Jianbing-D** [comment]
Hi @nrailgun, you can install SOK via `install.sh` following these commands, then there will be no further copying for you.
```shell
$ cd hugectr/sparse_operation_kit/
$ bash install.sh --SM=[Compute Capability] --USE_NVTX=[OFF/ON]
```

But we agree with you, install SOK via `pip` is more convenient for users. And we are working on it now.

**Comment by nrailgun** [comment]
> Hi @nrailgun , thank you for your suggestions! They are very valuable for us to improve our user experience.
> 
> > Currently sok shared library must be compiled and installed as root,
> 
> As we have provided NGC container for example in this release: "nvcr.io/nvidia/merlin/merlin-tensorflow-training:21.11",
> 
> * do you think it's sufficient or you need some solution like conda install or pip install?
> * If installing from source code is acceptable to you, how does install as root make things difficult?
> 
> > while the python scripts must be manually copied.
> 
> Which python scripts you want to copy?

1. Using community container is forbidden in my company.
2. I tried `bash install.sh`, but only the shared library is installed, while the hugectr sok python files are not (and I have to copy it to my `$PYTHONPATH`). Maybe it's a problem caused the linux distribution I am using (tlinux). I guess **maybe** install from wheel can solve this little problem.

**Comment by nrailgun** [comment]
> Hi @nrailgun, you can install SOK via `install.sh` following these commands, then there will be no further copying for you.
> 
> ```shell
> $ cd hugectr/sparse_operation_kit/
> $ bash install.sh --SM=[Compute Capability] --USE_NVTX=[OFF/ON]
> ```
> 
> But we agree with you, install SOK via `pip` is more convenient for users. And we are working on it now.

Thank you very much.

**Comment by Jianbing-D** [comment]
Hi @nrailgun , in this release, we added pip installation for SOK. And here are the [instructions](https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/sparse_operation_kit#install-this-module-from-pypi).
![image](https://user-images.githubusercontent.com/69858819/147208927-e9a74412-6bc2-4344-b17c-f88a409fa65a.png)

Would you like to try it to see whether it works for you?

**Comment by nrailgun** [comment]
> Hi @nrailgun , in this release, we added pip installation for SOK. And here are the [instructions](https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/sparse_operation_kit#install-this-module-from-pypi). ![image](https://user-images.githubusercontent.com/69858819/147208927-e9a74412-6bc2-4344-b17c-f88a409fa65a.png)
> 
> Would you like to try it to see whether it works for you?

Thank u very much!

**Comment by zehuanw** [comment]
Hi @nrailgun , is the problem on your side fixed? We would like to close this issue as you had positive feedback, but please reopen it if you still encounter the problem.
