### ISSUE TITLE
[Question] why use `control_dependencies` if I have multiple embeddings?

### ISSUE THREAD

**Issue by nrailgun** [NVIDIA-Merlin/HugeCTR#269]
I put the lookup of embedding_layers[0] in the loop and removed the `control_dependencies`, and the program crashed. But why?

```
        embedding_vector = tf.reshape(embedding_vector, shape=[-1, self.slot_num_list[0] * self.nnz_per_slot_list[0] * self.embedding_vec_size_list[0]])
        vectors.append(embedding_vector)

        for i in range(1, self.embedding_num):
            with tf.control_dependencies([embedding_vector]):
                embedding_vector = self.do_lookup(self.embedding_layers[i],
```
https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/sparse_operation_kit/documents/tutorials/DenseDemo/models.py#L276-L281

**Comment by Jianbing-D** [comment]
Cause TF is a multi-threaded module, where multiple CPU threads might be used to launch GPU kernels. And there are NCCL kernels inside SOK's embedding.

If no `control_dependencies`, and those embedding layers are independent, then the execution order might be different in different device, for example, 
```text
device-0: embedding-0 -> embedding-1
device-1: embedding-1 -> embedding-0
```
And this leads to deadlock.

Therefore, when there is no dependency between multiple embedding layers, `tf.control_dependencies` should be used to add control-dependencies among those embedding layers to force the deterministic execution order.

**Comment by nrailgun** [comment]
> Cause TF is a multi-threaded module, where multiple CPU threads might be used to launch GPU kernels. And there are NCCL kernels inside SOK's embedding.
> 
> If no `control_dependencies`, and those embedding layers are independent, then the execution order might be different in different device, for example,
> 
> ```
> device-0: embedding-0 -> embedding-1
> device-1: embedding-1 -> embedding-0
> ```
> 
> And this leads to deadlock.
> 
> Therefore, when there is no data dependency between multiple embedding layers, `tf.control_dependencies` should be used to add control-dependencies among those embedding layers to force the deterministic execution order.

I get it. Thanks.
