### ISSUE TITLE
[BUG] sok embedding initializer lost?

### ISSUE THREAD

**Issue by nrailgun** [NVIDIA-Merlin/HugeCTR#270]
I see `initial_value` in `EmbeddingVariable.__init__` args, but the `initial_value` is ignored in `All2AllDenseEmbedding.__init__`. And that makes uniform the only intializer.

**Comment by Jianbing-D** [comment]
Yes, currently, there a few initializers can be used in SOK, which are `uniform`, `zeros`, and `ones`.

We are going to support other types of initializers in the future.

Currently, you can use `load_embedding_values` to initialize the EmbedddingVariable as a workaround. 
https://nvidia-merlin.github.io/HugeCTR/sparse_operation_kit/v1.0.1/api/embeddings/saver.html#sparse_operation_kit.saver.Saver.Saver.load_embedding_values

**Comment by zehuanw** [comment]
Hi @nrailgun , TensorFlow Initializers are supported in HugeCTR v3.4: We now support the TensorFlow native initializer within SOK, such as sok.All2AllDenseEmbedding(embedding_initializer=tf.keras.initializers.RandomUniform()). For more information, refer to [All2All Dense Embedding](https://nvidia-merlin.github.io/HugeCTR/sparse_operation_kit/master/api/embeddings/dense/all2all.html).

I'd like to close this issue, but if you still encounter the problem please reopen it. Thank you for your feedback again!
