### ISSUE TITLE
[BUG] ColumnSelector object is not iterable

### ISSUE THREAD

**Issue by ShawnXuan** [NVIDIA-Merlin/HugeCTR#273]
**Describe the bug**
Error is raised when preprocess the dataset through NVTabular with command:
```
$ bash preprocess.sh 1 criteo_data nvt 1 0 1 # parquet output
```

```bash
Traceback (most recent call last):
  File "/nvtabular/nvtabular/workflow/workflow.py", line 505, in _transform_partition
    output_df = node.op.transform(node.input_columns, input_df)
  File "criteo_script/preprocess_nvt.py", line 67, in transform
    for col in columns:
TypeError: 'ColumnSelector' object is not iterable
```

**Additional context**
Fixed by change [preprocess_nvt.py#L66 `for col in columns:`](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/tools/criteo_script/preprocess_nvt.py#L66) to `for col in columns.names:`

**environment**
nvcr.io/nvidia/merlin/merlin-training:21.11 commit:8499f10347db

**Comment by jershi425** [comment]
Hi Shawn @ShawnXuan , thank you so much for your feedback.
Your proposed fix is correct and we have fixed our preprocessing scripts here: [commit](https://github.com/NVIDIA-Merlin/HugeCTR/commit/4d9c4adb72dd9d32f5f2ac697a9130d2a2d8f726). Now the preprocessing script can run without this issue. Thanks again!
