### ISSUE TITLE
[Question] how to add slot offset with nvt binary output dataset

### ISSUE THREAD

**Issue by ShawnXuan** [NVIDIA-Merlin/HugeCTR#274]
Binary output dataset is generated via `workflow.transform(train_ds_iterator).to_hugectr(...)` alone side with `parquet` format in `tools/criteo_script/preprocess_nvt.py`.
To use `parquet` format dataset, an option to add offset for each slot by specifying `slot_size_array`. How to add slot offset with nvt binary output dataset to avoid duplicate keys?

**Comment by jershi425** [comment]
@ShawnXuan Thank you for heads up! Right now HugeCTR only support `slot_size_array` for Parquet form. We would assume that the user is going to process the data into parquet format through NVTabular. Therefore, I would recommend using the `to_parquet(...)` method instead or using our pandas script to get binary data with `slot_size_array` added.

**Comment by ShawnXuan** [comment]
Thanks!
