### ISSUE TITLE
[BUG] Clarify NUMA affinity for devices in vvgpu Solver HugeCTR documentation

### ISSUE THREAD

**Issue by kshitizgupta21** [NVIDIA-Merlin/HugeCTR#280]
## Report needed documentation

**Report needed documentation**
There should be clarification of what we mean by nodes in documentation for `vvgpu` argument of `CreateSolver` method in `Solver` in HugeCTR
![image](https://user-images.githubusercontent.com/73861554/146289774-de9f7005-fb85-4da1-b18f-645352748a74.png)

By "nodes", are we referring to physical nodes here? Because when I tried training HugeCTR model on AWS EC2 p4d.24xlarge instance with 8 A100 40GB GPUs and specified `vvgpu=`[[0,1,2,3,4,5,6,7]]` I got this device to NUMA mapping even though I had just one physical node i.e. my pd4.24xlarge instance
```
Device to NUMA mapping:
  GPU 0 ->  node 0
  GPU 1 ->  node 0
  GPU 2 ->  node 0
  GPU 3 ->  node 0
  GPU 4 ->  node 1
  GPU 5 ->  node 1
  GPU 6 ->  node 1
  GPU 7 ->  node 1
``` 

This is why I think it would be very helpful for new users if there was discussion of the role NUMA affinity plays in the documentation of `vvgpu` in `CreateSolver`. It would certainly help make it less confusing.

**Comment by zehuanw** [comment]
Thank you for your feedback here! In the context of vvgpu and CreateSolver. we mean physical `node` (which can includes multiple NUMA nodes) not NUMA node. Hopes that my confirmation helps.

**Comment by zehuanw** [comment]
Please find the document fix on https://github.com/NVIDIA-Merlin/HugeCTR/commit/d7552c4c5f93ff18ded961645cac82d5d8b5b785.

**Comment by zehuanw** [comment]
Hi @kshitizgupta21, we'd like to close this issue as it's fixed in our document. Please reopen it if it doesn't solve your problem. Thanks!
