### ISSUE TITLE
[Question] Some questions in running DLRM sample

### ISSUE THREAD

**Issue by HydraZeng** [NVIDIA-Merlin/HugeCTR#284]
I am trying the DLRM sample in the main branch, where I face a few problems.

1. There is no docker "nvcr.io/nvidia/merlin/merlin-training:22.01" as listed in the README.md. To get around it, I use the lasted tag, i.e., 21.12 (https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-training/tags) instead.
2. When running command `dlrm_raw ./ ./ `  for kaggle dataset, it raises a **Segmentation fault**. `demesg` shows the message: `dlrm_raw[28741]: segfault at 8 ip 00007f8efc69daaf sp 00007fff4b869960 error 4 in libcudf.so[7f8efbc6f000+1ac0000]`

The GPU info is attached
![image](https://user-images.githubusercontent.com/17929524/148512945-a3b08358-fc1e-4d50-a935-b5fb84031203.png)

**Comment by HydraZeng** [comment]
Update:
It can work if using synthetic data by running `python3 ../tools/data_generator/dlrm_raw_generate_train.py`.

**Comment by zehuanw** [comment]
Thank you for the question! `nvcr.io/nvidia/merlin/merlin-training:22.01` will be available this week on NGC. 
dlrm_raw is hardcoded for Criteo 1TB dataset (https://labs.criteo.com/2013/12/download-terabyte-click-logs/). But it's a good suggestion to add kaggle too for the people who cannot download such large dataset.

**Comment by Jianbing-D** [comment]
Hi @HydraZeng , we can reproduce this error with `nvcr.io/nvidia/merlin/merlin-training:21.12`. 

But with `nvcr.io/nvidia/merlin/merlin-training:22.01`, there is no such error any more. And the log is:
```text
[HUGECTR][19:19:37][INFO][RANK0]: Processing Kaggle datasets
[HUGECTR][19:19:37][INFO][RANK0]: input_dir: ./
[HUGECTR][19:19:37][INFO][RANK0]: output_dir: ./
[HUGECTR][19:19:44][INFO][RANK0]: .//train.txt's total rows number = 45840617
[HUGECTR][19:19:44][INFO][RANK0]: Slot size array in .//train.txt, missing value mapped to unused key:
1459, 583, 6373320, 1977439, 305, 24, 12513, 633, 3, 92719, 5681, 5666265, 3193, 27, 14986, 4209368, 10, 5652, 2173, 4, 5058596, 18, 15, 282062, 105, 141594,
[HUGECTR][19:19:44][INFO][RANK0]: Time used to build map: 6308 milliseconds.
[HUGECTR][19:19:44][INFO][RANK0]: Total bytes read: 11147184845 Effective Read B/W: 1.645787 GB/s.
[HUGECTR][19:19:53][INFO][RANK0]: Porcessed file: .//train.txt for /train_data.bin
[HUGECTR][19:19:53][INFO][RANK0]: Size of train_data.bin: 5867598880 Bytes.
[HUGECTR][19:19:58][INFO][RANK0]: Size of val_data.bin: 733449920 Bytes.
[HUGECTR][19:20:03][INFO][RANK0]: Size of test_data.bin: 733449920 Bytes.
[HUGECTR][19:20:03][INFO][RANK0]: Processed file: .//train.txt for val_data.bin and test_data.bin
[HUGECTR][19:20:03][INFO][RANK0]: Time to process binaries: 18508 milliseconds.
[HUGECTR][19:20:03][INFO][RANK0]: Convert Bytes reading: 33441554535, Effective reading B/W: 1.682779 GB/s.
[HUGECTR][19:20:03][INFO][RANK0]: Convert Bytes writing: 7334498720, Effective reading B/W: 0.369072 GB/s.
[HUGECTR][19:20:03][INFO][RANK0]: Convert Bytes total: 40776053255, Effective reading B/W: 2.051851 GB/s.
[HUGECTR][19:20:03][INFO][RANK0]: Application process B/W: 0.417805 GB/s.
[HUGECTR][19:20:03][INFO][RANK0]: Done.
```

We recommend you use this docker image, since it is available now.

**Comment by zehuanw** [comment]
Hi @HydraZeng , per @Jianbing-D 's testing kaggle dataset is applicable in the release after 22.01. Would you like to have a try?

**Comment by HydraZeng** [comment]
> Hi @HydraZeng , per @Jianbing-D 's testing kaggle dataset is applicable in the release after 22.01. Would you like to have a try?

Thanks for your information. I will try this image!

**Comment by zehuanw** [comment]
Hi @HydraZeng , would you like to confirm if the issue is fixed? Thanks!

**Comment by HydraZeng** [comment]
Yes, sure. Thanks again for your kindly help.

**Comment by zehuanw** [comment]
Close as fixed
