### ISSUE TITLE
[Question] Inference on one parquet file

### ISSUE THREAD

**Issue by shoyasaxa** [NVIDIA-Merlin/HugeCTR#286]
Hello, 

Let's say we have one parquet file of 10,100 rows saved to `/usr/local/part_0.parquet`, and a `/usr/local/_file_list.txt` (like generated from NVT) for which the content is
```
1
/usr/local/part_0.parquet
``` 
and I'd like to get the predictions from a trained model for the data in this one parquet file. 

I am aware that we could use `hugectr.inference.InferenceSession.predict()` ([here](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/docs/python_interface.md#predict-method)) to do the predictions.

Let's also say our `batch_size` for inference is 1000. Then we could do 
```
predictions_list = inference_session.predict(
 num_batches=11, # ceil(10,100/1000)
 source="/usr/local/_file_list.txt",
 data_reader_type=hugectr.DataReaderType_t.Parquet,
 check_type=hugectr.Check_T.Non,
 slot_size_array=my_slot_size_array
)
```
However, this gives predictions for 11,000 rows because we specified 11 batches of 1000 rows, though the data only has 10,100 rows. Here, I have two questions
1. From the 11,000 rows, what are these 900 extra rows even though there should only be 10,100 rows in this file? Is it just the first 900 rows of this one parquet file again? 
2. If we only wanted predictions for 10,100 rows, could we simply do `predictions_list[:10100]` to get the correct predictions for all the rows of this file?
3. Just wanted to double check - does the first item in `predictions_list` (so `prediction_list[0]`) correspond with the output of the first row of `part_0.parquet`?

Thank you very much for your help!

**Comment by KingsleyLiu-NV** [comment]
Hi @shoyasaxa, thanks for your feedback regarding the inference Python interface. The API you used leverage the Parquet data reader of HugeCTR, which only supports the repeat mode during inference. That means when the data reader reaches the end of the file, it will go back to the first row of it. So the extra 900 rows in your case just correspond to the first 900 samples in `part_0.parquet`, and you can easily verify it by checking if `predictions_list[0:900]` is identical to `predictions_list[10100:11000]`.

The answers to you questions will be respectively:

1.  The inference Parquet data reader will always read `batch_size * num_batches` samples (1000*11 in your case). Yes, they are the first 900 samples in the file.
2.  Yes, `predictions_list[:10100]` should be results.
3.  Yes, the order in the inference results is complying with the order of samples in the parquet file.

**Comment by shoyasaxa** [comment]
Awesome - I just wanted to be sure. Thank you so much!
