### ISSUE TITLE
mutli-gpu training in one node failed.

### ISSUE THREAD

**Issue by dulvqingyunLT** [NVIDIA-Merlin/HugeCTR#287]
the training log and error as followed:

I have no name!@d93a12731a70:/hugectr/tools$ python ../samples/dcn/dcn_norm.py 
HugeCTR Version: 3.3
====================================================Model Init=====================================================
[HUGECTR][08:46:21][WARNING][RANK0]: The model name is not specified when creating the solver.
[HUGECTR][08:46:21][INFO][RANK0]: Global seed is 3554214936
[HUGECTR][08:46:21][INFO][RANK0]: Device to NUMA mapping:
  GPU 0 ->  node 0
  GPU 1 ->  node 0
  GPU 2 ->  node 0
  GPU 3 ->  node 0

Traceback (most recent call last):
  File "../samples/dcn/dcn_norm.py", line 24, in <module>
    model = hugectr.Model(solver, reader, optimizer)
RuntimeError: Runtime error: unhandled system error
        ncclGroupEnd() at ResourceManagerCore(/hugectr/HugeCTR/src/resource_managers/resource_manager_core.cpp:176)
I have no name!@d93a12731a70:/hugectr/tools$ 

I used the script from here:https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/samples/dcn/dcn.py

the docker container created by command "docker run --gpus=all --rm -it  --cap-add SYS_NICE -u $(id -u):$(id -g) -v $(pwd):/hugectr -w /hugectr nvcr.io/nvidia/merlin/merlin-training:21.12"

and my cuda enviroment is here:

Fri Jan 14 10:00:58 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.142.00   Driver Version: 450.142.00   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1B.0 Off |                    0 |
| N/A   26C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:00:1C.0 Off |                    0 |
| N/A   27C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            On   | 00000000:00:1D.0 Off |                    0 |
| N/A   28C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   27C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

when I used only 1 gpu card, it could run without errors,  but if i set the vvgpu = [[0,1,2,3]], i come out the error as above. Would any one tell me what's the problem?

**Comment by shijieliu** [comment]
Hi @dulvqingyunLT Thanks for trying HugeCTR! About your question, it looks like something in nccl wrong
`ncclGroupEnd() at ResourceManagerCore(/hugectr/HugeCTR/src/resource_managers/resource_manager_core.cpp:176)`
Could you try setting NCCL_DEBUG by `export NCCL_DEBUG=INFO`, rerun your scripts and share the log?

**Comment by dulvqingyunLT** [comment]
> export NCCL_DEBUG=INFO

Thanks a lot, I followed your tips and get the logs:
[nccl1.log](https://github.com/NVIDIA-Merlin/HugeCTR/files/7895968/nccl1.log)

**Comment by dulvqingyunLT** [comment]
> Hi @dulvqingyunLT Thanks for trying HugeCTR!
> 
> About your question, it looks like something in nccl wrong
> 
> ```
> ncclGroupEnd() at ResourceManagerCore(/hugectr/HugeCTR/src/resource_managers/resource_manager_core.cpp:176)
> ```
> 
> Could you try setting NCCL_DEBUG by `export NCCL_DEBUG=INFO`, rerun your scripts and share the log?

@shijieliu after mounting the /dev/shm from the host to the container problem solved, thank you~
