### ISSUE TITLE
question about using hugeCTR inference

### ISSUE THREAD

**Issue by dulvqingyunLT** [NVIDIA-Merlin/HugeCTR#288]
When i using the following settings to do inference,  there is an message " Parameter server lookup of 6920 / 6920 embeddings took ** us"
    inference_params = InferenceParams(model_name = model_name,
                                max_batchsize = 1000,
                                hit_rate_threshold = 1.0,
                                dense_model_file = dense_file,
                                sparse_model_files = embedding_file_list,
                                device_id = 0,
                                use_gpu_embedding_cache = True,
                                cache_size_percentage = 0.001,
                                i64_input_key = True,
                                use_mixed_precision = False
                                )

If i change use_gpu_embedding_cache to False, there is an message " Parameter server lookup of 26000 / 26000 embeddings took ** us". I think this makes sense because all the embeddings are in host memory, hugeCTR will look up all the 26000 embeddings in host memory.

 Why when I set use_gpu_embedding_cache to True , the embeddings reduced to 6920 but not 26000? I know that if I use GPU cache, part of the whole embeddings will loaded to the GPU memory, does it mean that the hugeCTR look up the 6920 embeddings in GPU memory ant the rest of embeddings in host memory? or hugeCTR removes the duplicated keys, get 6920 unique keys?

I use the data from criteo dataset for inference, and model is DLRM.

**Comment by yingcanw** [comment]
@dulvqingyunLT 

> Why when I set use_gpu_embedding_cache to True , the embeddings reduced to 6920 but not 26000? I know that if I use GPU cache, part of the whole embeddings will loaded to the GPU memory, does it mean that the hugeCTR look up the 6920 embeddings in GPU memory ant the rest of embeddings in host memory? or hugeCTR removes the duplicated keys, get 6920 unique keys?

Your understanding is correct. Assuming your batchsize is 1000, each sample needs to look up 26 embedding keys. 

- If use_gpu_embedding_cache  is not enabled, 100*26=26000 embedding keys will be looked up directly from PS

- If use_gpu_embedding_cache is enabled,  deduplicate operation will be performed on 26,000 embedded keys first. 
After deduplication, 10,000 unique embedded keys will be looked up directly from GPU embedding cache. Since the cache_size_percentage here is not 1, it means that if there are 6920 embedding keys(missing keys) not exist in embedding cache, PS  will complete the look up these missing embedding keys, and then  insert into embedding cache in asynchronous or synchronous mode according to the actual hit rate.

**Comment by dulvqingyunLT** [comment]
> @dulvqingyunLT
> 
> > Why when I set use_gpu_embedding_cache to True , the embeddings reduced to 6920 but not 26000? I know that if I use GPU cache, part of the whole embeddings will loaded to the GPU memory, does it mean that the hugeCTR look up the 6920 embeddings in GPU memory ant the rest of embeddings in host memory? or hugeCTR removes the duplicated keys, get 6920 unique keys?
> 
> Your understanding is correct. Assuming your batchsize is 1000, each sample needs to look up 26 embedding keys.
> 
> * If use_gpu_embedding_cache  is not enabled, 100*26=26000 embedding keys will be looked up directly from PS
> * If use_gpu_embedding_cache is enabled,  deduplicate operation will be performed on 26,000 embedded keys first.
>   After deduplication, 10,000 unique embedded keys will be looked up directly from GPU embedding cache. Since the cache_size_percentage here is not 1, it means that if there are 6920 embedding keys(missing keys) not exist in embedding cache, PS  will complete the look up these missing embedding keys, and then  insert into embedding cache in asynchronous or synchronous mode according to the actual hit rate.

Thank a lot, but I am not quite clear whether the 6920 embedding keys are the missing keys or hitting keys? the following logs indicate that the 6920 embedding keys look up is completed in cpu memory?

Looking up 6920 embeddings (each with 16 values)...
ParallelHashMap backend. Table: hctr_et.wdl.sparse_embedding1. Fetched 6920 / 6920 values.
ParallelHashMap: 6920 hits, 0 missing!
Parameter server lookup of 6920 / 6920 embeddings took 93 us.

**Comment by dulvqingyunLT** [comment]
> @dulvqingyunLT
> 
> > Why when I set use_gpu_embedding_cache to True , the embeddings reduced to 6920 but not 26000? I know that if I use GPU cache, part of the whole embeddings will loaded to the GPU memory, does it mean that the hugeCTR look up the 6920 embeddings in GPU memory ant the rest of embeddings in host memory? or hugeCTR removes the duplicated keys, get 6920 unique keys?
> 
> Your understanding is correct. Assuming your batchsize is 1000, each sample needs to look up 26 embedding keys.
> 
> * If use_gpu_embedding_cache  is not enabled, 100*26=26000 embedding keys will be looked up directly from PS
> * If use_gpu_embedding_cache is enabled,  deduplicate operation will be performed on 26,000 embedded keys first.
>   After deduplication, 10,000 unique embedded keys will be looked up directly from GPU embedding cache. Since the cache_size_percentage here is not 1, it means that if there are 6920 embedding keys(missing keys) not exist in embedding cache, PS  will complete the look up these missing embedding keys, and then  insert into embedding cache in asynchronous or synchronous mode according to the actual hit rate.

**Comment by yingcanw** [comment]
> Thank a lot, but I am not quite clear whether the 6920 embedding keys are the missing keys or hitting keys? the following logs indicate that the 6920 embedding keys look up is completed in cpu memory? and even I set cache_size_percentage = 1.0, there are still 6920 embedding keys look up, not zero embedding keys look up.
> 
> Looking up 6920 embeddings (each with 16 values)...
> ParallelHashMap backend. Table: hctr_et.wdl.sparse_embedding1. Fetched 6920 / 6920 values.
> ParallelHashMap: 6920 hits, 0 missing!
> Parameter server lookup of 6920 / 6920 embeddings took 93 us.

If the user enables embedding cache(EC), then any embedding keys looked up from PS can be regarded as missing embedding keys( not existing in EC). The `cache_size_percentage = 1.0`  just means that EC will be allocated the same size as the complete embedding table, but EC will not insert any embedding keys directly during initialization. So the first batch of embedding keys that still need to be looked up from PS (EC is empty), and then these missing embedding keys queried from PS will be inserted into EC. When the EC reaches the capacity limit, the LRU algorithm is enabled for insertion.
