### ISSUE TITLE
HugeCTR-2.1_beta/cub/cub/device/dispatch/../../agent/../thread/../util_ptx.cuh(276): error: identifier "__syncwarp" is undefined

### ISSUE THREAD

**Issue by yueyedeai** [NVIDIA-Merlin/HugeCTR#29]
HugeCTR-2.1_beta/cub/cub/device/dispatch/../../agent/../thread/../util_ptx.cuh(276): error: identifier "__syncwarp" is undefined
HugeCTR-2.1_beta/cub/cub/device/dispatch/../../agent/../thread/../util_ptx.cuh(287): error: identifier "__any_sync" is undefined
HugeCTR-2.1_beta/cub/cub/device/dispatch/../../agent/../thread/../util_ptx.cuh(300): error: identifier "__all_sync" is undefined
HugeCTR-2.1_beta/cub/cub/device/dispatch/../../agent/../thread/../util_ptx.cuh(313): error: identifier "__ballot_sync" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_0000e907_00000000-6_embedding_creator.cpp1.ii".
HugeCTR/src/CMakeFiles/huge_ctr_static.dir/build.make:101: recipe for target 'HugeCTR/src/CMakeFiles/huge_ctr_static.dir/embedding_creator.cu.o' failed
make[2]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/embedding_creator.cu.o] Error 1
CMakeFiles/Makefile2:156: recipe for target 'HugeCTR/src/CMakeFiles/huge_ctr_static.dir/all' failed
make[1]: *** [HugeCTR/src/CMakeFiles/huge_ctr_static.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Jianbing-D** [comment]
What is the compile environment? Did you use this [docker image](https://github.com/NVIDIA/HugeCTR#use-docker-container)?

**Comment by yueyedeai** [comment]
@Jianbing-D  Sending build context to Docker daemon  542.9MB
Step 1/7 : FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
 ---> 2b8bb5f68029
Step 2/7 : RUN apt-get update &&     apt-get upgrade -y
 ---> Using cache
 ---> 744a8c7d8b9d
Step 3/7 : RUN apt-get install -y     git     cmake     vim     wget     clang-format     python3-pip
 ---> Running in d60cc2c99172
Reading package lists...
Building dependency tree...
Reading state information...
Package git is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package cmake is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'git' has no installation candidate
E: Package 'cmake' has no installation candidate
E: Unable to locate package vim
E: Unable to locate package wget
E: Unable to locate package clang-format
E: Unable to locate package python3-pip

**Comment by Jianbing-D** [comment]
> @Jianbing-D Sending build context to Docker daemon 542.9MB
> Step 1/7 : FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
> ---> 2b8bb5f68029
> Step 2/7 : RUN apt-get update && apt-get upgrade -y
> ---> Using cache
> ---> 744a8c7d8b9d
> Step 3/7 : RUN apt-get install -y git cmake vim wget clang-format python3-pip
> ---> Running in d60cc2c99172
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Package git is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> Package cmake is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'git' has no installation candidate
> E: Package 'cmake' has no installation candidate
> E: Unable to locate package vim
> E: Unable to locate package wget
> E: Unable to locate package clang-format
> E: Unable to locate package python3-pip

Is these the errors during build this [dockerfile](https://github.com/NVIDIA/HugeCTR/blob/master/tools/dockerfiles/dev.Dockerfile)?

**Comment by zehuanw** [comment]
Hi @yueyedeai , we are closing this issue, if you still encounter the problem on our latest container, we will appreciate if you can create an new issue. Thanks!
