### ISSUE TITLE
question of  single model multi-gpu deployment

### ISSUE THREAD

**Issue by dulvqingyunLT** [NVIDIA-Merlin/HugeCTR#293]
I used sparse feature like criteo dataset, with vec_size=64, so the footprint of the embedding table is about 45 gigabytes. 
I wanted to deploy the DLRM inference on a machine(4xT4 gpu, each gpu has 15G Mem, and the machine has 200G host memory). the ps.json file is as follows:

{
    "supportlonglong":true,
    "db_type": "local",
    "models":[
        {
            "model":"dlrm",
            "sparse_files":["/hugectr/samples/model_repo/dlrm/2/dlrm_etc_vec64_sparse.model"],
            "dense_file":"/hugectr/samples/model_repo/dlrm/2/dlrm_etc_vec64_dense_0.model",
            "network_file":"/hugectr/samples/model_repo/dlrm/2/dlrm_etc_vec64.json",
            "num_of_worker_buffer_in_pool": "4",
            "num_of_refresher_buffer_in_pool":"1",
            "deployed_device_list":["0","1","2","3"],
            "max_batch_size":"10000",
            "default_value_for_each_table":["0.0","0.0"],
            "hit_rate_threshold":"0.9",
            "gpucacheper":"0.2",
            "gpucache":"true",
            "cache_refresh_percentage_per_iteration":0.2
        }
    ]  
}
--------------------------------------
the config.pbtxt as follows:

name: "dlrm"
backend: "hugectr"
max_batch_size:10000,

input [
   {
    name: "DES"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "CATCOLUMN"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "ROWINDEX"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
instance_group [
  {
    count: 1
    kind : KIND_GPU
    gpus:[0,1,2,3]
  }
]

parameters [
  {
  key: "config"
  value: { string_value: "/hugectr/samples/model_repo/dlrm/1/dlrm_etc_vec64.json" }
  },
  {
  key: "gpucache"
  value: { string_value: "true" }
  },
  {
  key: "hit_rate_threshold"
  value: { string_value: "0.8" }
  },
  {
  key: "gpucacheper"
  value: { string_value: "0.1" }
  },
  {
  key: "label_dim"
  value: { string_value: "1" }
  },
  {
  key: "slots"
  value: { string_value: "26" }
  },
  {
  key: "cat_feature_num"
  value: { string_value: "26" }
  },
 {
  key: "des_feature_num"
  value: { string_value: "13" }
  },
  {
  key: "max_nnz"
  value: { string_value: "2" }
  },
  {
  key: "embedding_vector_size"
  value: { string_value: "64" }
  },
  {
  key: "embeddingkey_long_type"
  value: { string_value: "true" }
  }
]
---------------------------

when i tested using perf_analyzer i found that the 4 gpu worked independently. The log as follows:

I0121 07:46:00.300815 47939 grpc_server.cc:4117] Started GRPCInferenceService at 0.0.0.0:8001
I0121 07:46:00.301031 47939 http_server.cc:2815] Started HTTPService at 0.0.0.0:8000
I0121 07:46:00.343048 47939 http_server.cc:167] Started Metrics Service at 0.0.0.0:8002
I0121 08:29:07.290591 47939 hugectr.cc:1622] model dlrm, instance dlrm, executing 1 requests
I0121 08:29:07.290636 47939 hugectr.cc:1687] request 0: id = "", correlation_id = 0, input_count = 3, requested_output_count = 1
I0121 08:29:07.290656 47939 hugectr.cc:1776]    input CATCOLUMN: datatype = INT64, shape = [1,26], byte_size = 208000, buffer_count = 1
I0121 08:29:07.290665 47939 hugectr.cc:1788]    input ROWINDEX: datatype = INT32, shape = [1,27], byte_size = 104004, buffer_count = 1
I0121 08:29:07.290674 47939 hugectr.cc:1800]    input DES: datatype = FP32, shape = [1,13], byte_size = 52000, buffer_count = 1
I0121 08:29:07.290683 47939 hugectr.cc:1818]    requested_output OUTPUT0
I0121 08:29:07.290902 47939 hugectr.cc:1960] *****Processing request on device***** 0 for model dlrm
[HUGECTR][08:29:07][INFO][RANK0]: *****Insert embedding cache of model dlrm on device 0*****
[HUGECTR][08:29:07][INFO][RANK0]: Looking up 6920 embeddings (each with 64 values)...
[HUGECTR][08:29:07][DEBUG][RANK0]: ParallelHashMap backend. Table: hctr_et.dlrm.sparse_embedding1. Fetched 6920 / 6920 values.
[HUGECTR][08:29:07][DEBUG][RANK0]: ParallelHashMap: 6920 hits, 0 missing!
[HUGECTR][08:29:07][INFO][RANK0]: Parameter server lookup of 6920 / 6920 embeddings took 1287 us.
I0121 08:29:07.317932 47939 hugectr.cc:1967] ******Processing request completed!******
I0121 08:29:07.317997 47939 hugectr.cc:1978] Prediction execution time is 27 ms
I0121 08:29:07.319082 47939 hugectr.cc:1622] model dlrm, instance dlrm, executing 1 requests
I0121 08:29:07.319114 47939 hugectr.cc:1687] request 0: id = "", correlation_id = 0, input_count = 3, requested_output_count = 1
I0121 08:29:07.319133 47939 hugectr.cc:1776]    input CATCOLUMN: datatype = INT64, shape = [1,26], byte_size = 208000, buffer_count = 1
I0121 08:29:07.319145 47939 hugectr.cc:1788]    input ROWINDEX: datatype = INT32, shape = [1,27], byte_size = 104004, buffer_count = 1
I0121 08:29:07.319154 47939 hugectr.cc:1800]    input DES: datatype = FP32, shape = [1,13], byte_size = 52000, buffer_count = 1
I0121 08:29:07.319164 47939 hugectr.cc:1818]    requested_output OUTPUT0
I0121 08:29:07.319360 47939 hugectr.cc:1960] *****Processing request on device***** 1 for model dlrm
[HUGECTR][08:29:07][INFO][RANK0]: *****Insert embedding cache of model dlrm on device 1*****
[HUGECTR][08:29:07][INFO][RANK0]: Looking up 6920 embeddings (each with 64 values)...
[HUGECTR][08:29:07][DEBUG][RANK0]: ParallelHashMap backend. Table: hctr_et.dlrm.sparse_embedding1. Fetched 6920 / 6920 values.
[HUGECTR][08:29:07][DEBUG][RANK0]: ParallelHashMap: 6920 hits, 0 missing!
[HUGECTR][08:29:07][INFO][RANK0]: Parameter server lookup of 6920 / 6920 embeddings took 534 us.
I0121 08:29:07.345495 47939 hugectr.cc:1967] ******Processing request completed!******
I0121 08:29:07.345562 47939 hugectr.cc:1978] Prediction execution time is 26 ms
I0121 08:29:07.346276 47939 hugectr.cc:1622] model dlrm, instance dlrm, executing 1 requests
I0121 08:29:07.346305 47939 hugectr.cc:1687] request 0: id = "", correlation_id = 0, input_count = 3, requested_output_count = 1
I0121 08:29:07.346329 47939 hugectr.cc:1776]    input CATCOLUMN: datatype = INT64, shape = [1,26], byte_size = 208000, buffer_count = 1
I0121 08:29:07.346340 47939 hugectr.cc:1788]    input ROWINDEX: datatype = INT32, shape = [1,27], byte_size = 104004, buffer_count = 1
I0121 08:29:07.346349 47939 hugectr.cc:1800]    input DES: datatype = FP32, shape = [1,13], byte_size = 52000, buffer_count = 1
I0121 08:29:07.346357 47939 hugectr.cc:1818]    requested_output OUTPUT0
I0121 08:29:07.346532 47939 hugectr.cc:1960] *****Processing request on device***** 2 for model dlrm
[HUGECTR][08:29:07][INFO][RANK0]: *****Insert embedding cache of model dlrm on device 2*****
[HUGECTR][08:29:07][INFO][RANK0]: Looking up 6920 embeddings (each with 64 values)...
[HUGECTR][08:29:07][DEBUG][RANK0]: ParallelHashMap backend. Table: hctr_et.dlrm.sparse_embedding1. Fetched 6920 / 6920 values.
[HUGECTR][08:29:07][DEBUG][RANK0]: ParallelHashMap: 6920 hits, 0 missing!
[HUGECTR][08:29:07][INFO][RANK0]: Parameter server lookup of 6920 / 6920 embeddings took 444 us.
I0121 08:29:07.372569 47939 hugectr.cc:1967] ******Processing request completed!******
I0121 08:29:07.372620 47939 hugectr.cc:1978] Prediction execution time is 26 ms
I0121 08:29:07.373420 47939 hugectr.cc:1622] model dlrm, instance dlrm, executing 1 requests
I0121 08:29:07.372569 47939 hugectr.cc:1967] ******Processing request completed!******
I0121 08:29:07.372620 47939 hugectr.cc:1978] Prediction execution time is 26 ms
I0121 08:29:07.373420 47939 hugectr.cc:1622] model dlrm, instance dlrm, executing 1 requests
I0121 08:29:07.373450 47939 hugectr.cc:1687] request 0: id = "", correlation_id = 0, input_count = 3, requested_output_count = 1
I0121 08:29:07.373466 47939 hugectr.cc:1776]    input CATCOLUMN: datatype = INT64, shape = [1,26], byte_size = 208000, buffer_count = 1
I0121 08:29:07.373477 47939 hugectr.cc:1788]    input ROWINDEX: datatype = INT32, shape = [1,27], byte_size = 104004, buffer_count = 1
I0121 08:29:07.373487 47939 hugectr.cc:1800]    input DES: datatype = FP32, shape = [1,13], byte_size = 52000, buffer_count = 1
I0121 08:29:07.373495 47939 hugectr.cc:1818]    requested_output OUTPUT0
I0121 08:29:07.373664 47939 hugectr.cc:1960] *****Processing request on device***** 3 for model dlrm
[HUGECTR][08:29:07][INFO][RANK0]: *****Insert embedding cache of model dlrm on device 3*****
[HUGECTR][08:29:07][INFO][RANK0]: Looking up 6920 embeddings (each with 64 values)...
[HUGECTR][08:29:07][DEBUG][RANK0]: ParallelHashMap backend. Table: hctr_et.dlrm.sparse_embedding1. Fetched 6920 / 6920 values.
[HUGECTR][08:29:07][DEBUG][RANK0]: ParallelHashMap: 6920 hits, 0 missing!
[HUGECTR][08:29:07][INFO][RANK0]: Parameter server lookup of 6920 / 6920 embeddings took 419 us.
I0121 08:29:07.399595 47939 hugectr.cc:1967] ******Processing request completed!******
I0121 08:29:07.399644 47939 hugectr.cc:1978] Prediction execution time is 25 ms
I0121 08:29:07.400512 47939 hugectr.cc:1622] model dlrm, instance dlrm, executing 1 requests
I0121 08:29:07.400539 47939 hugectr.cc:1687] request 0: id = "", correlation_id = 0, input_count = 3, requested_output_count = 1
I0121 08:29:07.400554 47939 hugectr.cc:1776]    input CATCOLUMN: datatype = INT64, shape = [1,26], byte_size = 208000, buffer_count = 1
I0121 08:29:07.400565 47939 hugectr.cc:1788]    input ROWINDEX: datatype = INT32, shape = [1,27], byte_size = 104004, buffer_count = 1
I0121 08:29:07.400574 47939 hugectr.cc:1800]    input DES: datatype = FP32, shape = [1,13], byte_size = 52000, buffer_count = 1
I0121 08:29:07.400582 47939 hugectr.cc:1818]    requested_output OUTPUT0
I0121 08:29:07.400711 47939 hugectr.cc:1960] *****Processing request on device***** 0 for model dlrm
[HUGECTR][08:29:07][INFO][RANK0]: *****Insert embedding cache of model dlrm on device 0*****
I0121 08:29:07.425368 47939 hugectr.cc:1967] ******Processing request completed!******
I0121 08:29:07.425420 47939 hugectr.cc:1978] Prediction execution time is 24 ms
I0121 08:29:07.426326 47939 hugectr.cc:1622] model dlrm, instance dlrm, executing 1 requests
I0121 08:29:07.426354 47939 hugectr.cc:1687] request 0: id = "", correlation_id = 0, input_count = 3, requested_output_count = 1
I0121 08:29:07.426368 47939 hugectr.cc:1776]    input CATCOLUMN: datatype = INT64, shape = [1,26], byte_size = 208000, buffer_count = 1
I0121 08:29:07.426386 47939 hugectr.cc:1788]    input ROWINDEX: datatype = INT32, shape = [1,27], byte_size = 104004, buffer_count = 1
I0121 08:29:07.426395 47939 hugectr.cc:1800]    input DES: datatype = FP32, shape = [1,13], byte_size = 52000, buffer_count = 1
I0121 08:29:07.426403 47939 hugectr.cc:1818]    requested_output OUTPUT0
I0121 08:29:07.426542 47939 hugectr.cc:1960] *****Processing request on device***** 1 for model dlrm
[HUGECTR][08:29:07][INFO][RANK0]: *****Insert embedding cache of model dlrm on device 1*****
I0121 08:29:07.451178 47939 hugectr.cc:1967] ******Processing request completed!******
I0121 08:29:07.451221 47939 hugectr.cc:1978] Prediction execution time is 24 ms
I0121 08:29:07.452002 47939 hugectr.cc:1622] model dlrm, instance dlrm, executing 1 requests
I0121 08:29:07.452029 47939 hugectr.cc:1687] request 0: id = "", correlation_id = 0, input_count = 3, requested_output_count = 1
I0121 08:29:07.452044 47939 hugectr.cc:1776]    input CATCOLUMN: datatype = INT64, shape = [1,26], byte_size = 208000, buffer_count = 1
I0121 08:29:07.452055 47939 hugectr.cc:1788]    input ROWINDEX: datatype = INT32, shape = [1,27], byte_size = 104004, buffer_count = 1
I0121 08:29:07.452065 47939 hugectr.cc:1800]    input DES: datatype = FP32, shape = [1,13], byte_size = 52000, buffer_count = 1
I0121 08:29:07.452073 47939 hugectr.cc:1818]    requested_output OUTPUT0
I0121 08:29:07.452239 47939 hugectr.cc:1960] *****Processing request on device***** 2 for model dlrm
[HUGECTR][08:29:07][INFO][RANK0]: *****Insert embedding cache of model dlrm on device 2*****
I0121 08:29:07.476882 47939 hugectr.cc:1967] ******Processing request completed!******

-----------------------
from the above log we can see each gpu cache store the independently embedding vector, not see any cross gpu embedding look up. When I set "gpucacheper":"0.5" in ps.json, an OOM error will raise.  but as far as i know, the total gpu memory of the 4 gpu is 60G, If I want each GPU share the cache with other gpu's cache,  How can I DO?  I do not find samples of deploy one model instance to multi-gpu here: https://github.com/triton-inference-server/hugectr_backend/tree/main/samples

**Comment by yingcanw** [comment]
> from the above log we can see each gpu cache store the independently embedding vector, not see any cross gpu embedding look up. When I set "gpucacheper":"0.5" in ps.json, an OOM error will raise. but as far as i know, the total gpu memory of the 4 gpu is 60G, If I want each GPU share the cache with other gpu's cache, How can I DO? I do not find samples of deploy one model instance to multi-gpu here: https://github.com/triton-inference-server/hugectr_backend/tree/main/samples

The log display is correct, which means that hugectr_backend does not support embedding cache sharing across GPUs. You can refer   [hugectr-backend-framework](https://github.com/triton-inference-server/hugectr_backend/blob/main/docs/architecture.md#hugectr-backend-framework) for details. You can understand that each model loads a separate embedding cache for each embedding table on each GPU, which means that multiple model instances(belonging to the same model) on the same GPU can share the embedding cache of the same embedding table. This is why the oom is caused when set "gpucacheper":"0.5" .

**Comment by dulvqingyunLT** [comment]
@yingcanw 
> The log display is correct, which means that hugectr_backend does not support embedding cache sharing across GPUs. You can refer [hugectr-backend-framework](https://github.com/triton-inference-server/hugectr_backend/blob/main/docs/architecture.md#hugectr-backend-framework) for details. You can understand that each model loads a separate embedding cache for each embedding table on each GPU, which means that multiple model instances(belonging to the same model) on the same GPU can share the embedding cache of the same embedding table. This is why the oom is caused when set "gpucacheper":"0.5" .

Thank you so much!  So the hugectr-backend-framework does not support model parallelism like  the hugeCTR training framework?  Another question is that if I use hugeCTR for training with Embedding Training Cache, the cache here is shared by all the GPU, or independently just like in  hugectr-backend-framework?

**Comment by yingcanw** [comment]
> Thank you so much! So the hugectr-backend-framework does not support model parallelism like the hugeCTR training framework?
If utilizing Redis cluster deployments for Distributed Database, the hugectr-backend-framework supports model parallelism on Hierarchical inference PS instead of GPU embedding cache.

> Another question is that if I use hugeCTR for training with Embedding Training Cache, the cache here is shared by all the GPU, or independently just like in hugectr-backend-framework?
ETC shared by all the GPUs.

**Comment by dulvqingyunLT** [comment]
@yingcanw . Thanks. So Is there any plan to add the feature of 'embedding cache sharing across GPUs' to hugeCTR backend?

**Comment by yingcanw** [comment]
Although **embedding cache sharing across GPUs**  can expand the capacity of GPU cache, it also has many disadvantages:

- Inference services deployed in the production environment must be highly available, and each inference node needs to deploy inference services for multiple models. That is to say, the memory sharing of multiple GPUs will inevitably pose a serious challenge to resource isolation.

- The locality of recommendation data imposes strict requirements on data distribution in multiple GPUs, any changes in the distribution of request traffic can easily lead to data skew.

Therefore, we will solve the above problems from the HPS architectural, please look forward to！

**Comment by zehuanw** [comment]
Hi @dulvqingyunLT , we are wondering if @yingcanw reply solves your problem? Thanks!

**Comment by viswa-nvidia** [comment]
retiring this ticket

**Comment by sezhiyanhari** [comment]
@yingcanw thank you for the answers above!

I just want to make sure my understanding is correct. The HugeCTR HPS backend allows a single model to be replicated across multiple GPUs, meaning each GPU independently performs inference on the same model. So if we have N GPUs, we should get roughly get N times the inference throughput. But the HPS backend does not support GPU-GPU communication over NVLink/NVSwitch/another interconnect to allow one GPU to access embeddings on another.

Is that correct?
