### ISSUE TITLE
[BUG] Can't import sparse operation kit in nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.02

### ISSUE THREAD

**Issue by cmgreen210** [NVIDIA-Merlin/HugeCTR#296]
**Describe the bug**
Can't import sparse operation kit in nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.02

**To Reproduce**
1. How to build including `docker pull & docker run` commands
docker run -it nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.02 python3 -c "import sparse_operation_kit as sok"

**Expected behavior**
Shouldn't fail.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu xx.yy]
 - Graphic card: [e.g. a single NVIDIA V100 or NVIDIA DGX A100]
 - CUDA version: [e.g. CUDA 11.x]
 - Docker image

**Additional context**
Stack trace 

> 
> ================
> == TensorFlow ==
> ================
> 
> NVIDIA Release 22.01-tf2 (build 31081301)
> TensorFlow Version 2.7.0
> 
> Container image Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
> Copyright 2017-2022 The TensorFlow Authors.  All rights reserved.
> 
> Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
> 
> This container image and its contents are governed by the NVIDIA Deep Learning Container License.
> By pulling and using the container, you accept the terms and conditions of this license:
> https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
> 
> WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
>    Use the NVIDIA Container Toolkit to start this container with GPU support; see
>    https://docs.nvidia.com/datacenter/cloud-native/ .
> 
> NOTE: MOFED driver for multi-node communication was not detected.
>       Multi-node communication performance may be reduced.
> 
> NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
>    insufficient for TensorFlow.  NVIDIA recommends the use of the following flags:
>    docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ...
> 
> [INFO]: sparse_operation_kit is imported
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python3.8/dist-packages/SparseOperationKit-1.1.1-py3.8-linux-x86_64.egg/sparse_operation_kit/__init__.py", line 19, in <module>
>     from sparse_operation_kit.core._version import __version__
>   File "/usr/local/lib/python3.8/dist-packages/SparseOperationKit-1.1.1-py3.8-linux-x86_64.egg/sparse_operation_kit/core/__init__.py", line 22, in <module>
>     from sparse_operation_kit.core.embedding_variable_v2 import EmbeddingVariable
>   File "/usr/local/lib/python3.8/dist-packages/SparseOperationKit-1.1.1-py3.8-linux-x86_64.egg/sparse_operation_kit/core/embedding_variable_v2.py", line 31, in <module>
>     from tensorflow.distribute import get_strategy, has_strategy
> ImportError: cannot import name 'get_strategy' from 'tensorflow.distribute' (/usr/local/lib/python3.8/dist-packages/tensorflow/distribute/__init__.py)

**Comment by cmgreen210** [comment]
Works fine for `nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.01`

**Comment by bashimao** [comment]
@cmgreen210 That went faster than expected. Can you try checking out the https://github.com/NVIDIA-Merlin/HugeCTR/commits/master to see if that fixes your problem?

**Comment by bashimao** [comment]
Closing. Officially fixed in [v3.4.1](https://github.com/NVIDIA-Merlin/HugeCTR/releases/tag/v3.4.1).
