### ISSUE TITLE
Runtime error: out of memory /mnt/HugeCTR/HugeCTR/include/general_buffer.hpp:64

### ISSUE THREAD

**Issue by TimJZ** [NVIDIA-Merlin/HugeCTR#30]
Hi, when I was trying to run DLRM with terabyte dataset with one GPU, I got a runtime error message like this. My guess is I ran out of my GPU memory. I've also tried to decrease the mini batch size or batchsize_eval but still get this error. Does anyone know how to solve this issue? 

I was running the following command: 
./huge_ctr --train ./dlrm_fp16_64k.json

And the solver in my dlrm_fp16_64k.json looks like this: 
"solver": {
    "lr_policy": "fixed",
    "display": 1000,
    "max_iter":64013,
    "gpu": [0],
    "batchsize": 1024,
    "batchsize_eval": 131072,
    "snapshot": 10000000,
    "snapshot_prefix": "./",
    "eval_interval": 3200,
    "eval_batches": 681,
    "mixed_precision": 1024,
    "eval_metrics": ["AUC:0.8025"]
  }

**Comment by XiaoleiShi-NV** [comment]
HugeCTR will store the embedding table on device memory: the terabyte DLRM will need at least 90+GB, and the size of embedding depends on the vocabulary size, not batch size, so the momory of a single GPU is not big enough.

**Comment by bashimao** [comment]
@TimJZ Training large models that exceed device memory - like in the described case - can now be trained using HugeCTR using the EmbeddingCache's **Cached-PS** mode. For further information and how to setup, see [here](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/docs/hugectr_embedding_training_cache.md).
