### ISSUE TITLE
[Question] Extract embedding weights from SOK layers

### ISSUE THREAD

**Issue by adilism** [NVIDIA-Merlin/HugeCTR#300]
What is the most effient way to extract embedding weights to Tensorflow tensors/NumPy arrays from either `All2AllDenseEmbedding` layer or the outputs of the Saver? 

The workaround I found for now is collecting outputs of `call()` method

**Comment by Jianbing-D** [comment]
@kunlunl Please take a look to this issue.

**Comment by kunlunl** [comment]
It's true that the `call()` method is the only way to get the weights for now.

**Comment by adilism** [comment]
Thanks for the reply - would be a handy feature to have
