### ISSUE TITLE
[BUG] sok.Init() failed when it is not under a tf distributed strategy

### ISSUE THREAD

**Issue by cockroachzl** [NVIDIA-Merlin/HugeCTR#302]
**Describe the bug**

sok.Init() failed when it is not under a tf distributed strategy. However, it works fine if sok.Init() is invoked under a TF distributed strategy, such as the following code.
```python
strategy = tf.distribute.MirroredStrategy()

with strategy.scope():
    sok.Init(global_batch_size=65536)
```

**To Reproduce**
1. How to build including `docker pull & docker run` commands
```bash
git clone https://github.com/NVIDIA-Merlin/HugeCTR
python setup.py install
```
2. How to run including the JSON config file used
The following code snippet could reproduce this issue:
```python
import tensorflow as tf
import sparse_operation_kit as sok

gpus = tf.config.list_physical_devices('GPU')
gpu = gpus[0]
tf.config.set_visible_devices(gpu, 'GPU')
tf.config.experimental.set_memory_growth(gpu, True)

sok.Init(global_batch_size=65536)
```
The stack trace is 
```
---------------------------------------------------------------------------
AbortedError                              Traceback (most recent call last)
<ipython-input-3-9a4771e3095a> in <module>
----> 1 sok.Init(global_batch_size=65536)

/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/SparseOperationKit-1.1.2-py3.8-linux-x86_64.egg/sparse_operation_kit/core/initialize.py in Init(**kwargs)
    235     else:
    236         # horovod not imported
--> 237         return _one_device_init(**kwargs)

/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/SparseOperationKit-1.1.2-py3.8-linux-x86_64.egg/sparse_operation_kit/core/initialize.py in _one_device_init(**kwargs)
    196         global_seed = kwargs.get("seed", None) or kit_lib.gen_random_seed()
    197         visible_devices = _get_visible_devices()
--> 198         status = kit_lib.plugin_init(local_rank, 1, unique_id, global_seed, visible_devices,
    199                                      global_batch_size=kwargs["global_batch_size"])
    200         return status

<string> in plugin_init(global_replica_id, num_replicas_in_sync, nccl_unique_id, global_seed, visible_devices, global_batch_size, name)

/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   7184 def raise_from_not_ok_status(e, name):
   7185   e.message += (" name: " + name if name is not None else "")
-> 7186   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   7187 
   7188 

AbortedError: /workspace/user_code/HugeCTR/sparse_operation_kit/kit_cc/kit_cc_infra/src/resources/cpu_resource.cc:47 Intra-process barrier blocking threads time out. [Op:PluginInit]
```
**Expected behavior**

I expect sok.Init works without any TF distributed strategy in an A100 GPU, for in our current situation, training our recommender ranking model with only one A100 GPU is already enough.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu xx.yy] CentOS 7
 - Graphic card: [e.g. a single NVIDIA V100 or NVIDIA DGX A100] 2 A100 GPUs, each with 40GB memory
 - CUDA version: [e.g. CUDA 11.x] 11.2
 - Docker image: Build from latest source code
 - CUDNN version: 8.2
 - TF Version: 2.8.0

**Additional context**

**Comment by tonyf** [comment]
Having the same issue here

**Comment by Jianbing-D** [comment]
@kunlunl Please take a look to this issue.

**Comment by kunlunl** [comment]
@cockroachzl could you double check if you add `tf.config.set_visible_devices(gpu, 'GPU')` when you got the "Intra-process barrier blocking threads time out" error? I tested on my own environment with the following code and it ran successfully.
```python
import tensorflow as tf
import sparse_operation_kit as sok

gpus = tf.config.list_physical_devices('GPU')
gpu = gpus[0]
tf.config.set_visible_devices(gpu, 'GPU')
tf.config.experimental.set_memory_growth(gpu, True)

sok.Init(global_batch_size=65536)
```

However, when I removed the `tf.config.set_visible_devices(gpu, 'GPU')`, I can see the "Intra-process barrier blocking threads time out" error.

**Comment by zehuanw** [comment]
Hi @cockroachzl @tonyf , we are wondering if the issue is solved from your side? Thanks!
