### ISSUE TITLE
Why HugeCTR doesn't support FTRL optimizer which is widely used at recommender system? 

### ISSUE THREAD

**Issue by AtekiRyu** [NVIDIA-Merlin/HugeCTR#303]
Why HugeCTR doesn't support FTRL optimizer which is widely used at recommender system? 
Is there some design limitation that makes FTRL is hard to implement at HugeCTR?

**Comment by snowmanwwg** [comment]
Thank you for the feedback. We are actively researching about this to add to our roadmap, and will keep you posted.

**Comment by WonderingWJ** [comment]
We have already support FTRL optimizer
https://github.com/NVIDIA-Merlin/HugeCTR/blob/main/HugeCTR/include/optimizers/ftrl_optimizer.hpp

**Comment by WonderingWJ** [comment]
Hi @AtekiRyu , I'm glad to let you know that we just supported FTRL optimizer and here is how to use it.
```
optimizer = hugectr.CreateOptimizer(
    optimizer_type=hugectr.Optimizer_t.Ftrl,
    update_type=hugectr.Update_t.Global,
    beta = 0.0f,
    lambda1=0.0f,
    lambda2=0.0f,
)
```
 You can find it in the latest released container `nvcr.io/nvidia/merlin/merlin-hugectr:22.12`
 Feel free to comment

**Comment by bashimao** [comment]
Closing this for now. @AtekiRyu Please don't hesitate to reopen this ticket if you have trouble using or face performance issues with the FTRL or any other optimizer.
