### ISSUE TITLE
[BUG] Documentation links broken

### ISSUE THREAD

**Issue by colin2328** [NVIDIA-Merlin/HugeCTR#304]
I'm trying to read more about HugeCTR, and as I've been poking around I'm finding that some of the documentation is broken:

e.g most of the links on this page 404: https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/tutorial/multinode-training

I also noticed the link ot the documentation is broken: (first link here: https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/docs) I think it's meant to point to  https://nvidia-merlin.github.io/HugeCTR/master/api/python_interface.html?

**Comment by jershi425** [comment]
Hi Colin @colin2328, 

Thank you for pointing this out! Now the page 404 issues have been solved. And the link to the documentation is also fixed. Please let me know if you have any other concern.

Thanks again,
Jerry
