### ISSUE TITLE
A Typo Error

### ISSUE THREAD

**Issue by MARD1NO** [NVIDIA-Merlin/HugeCTR#308]
https://github.com/NVIDIA-Merlin/HugeCTR/blob/fab0993da7caa1536b1035114f94eb14c4289c86/HugeCTR/src/layers/fused_relu_bias_fully_connected_layer.cu#L190 

here：
```python
Set it to 8MB for now -> Set it to 16MB for now
```

**Comment by zehuanw** [comment]
Thank you for the feedback! @MARD1NO Please find the fix under https://github.com/NVIDIA-Merlin/HugeCTR/pull/309.
