### ISSUE TITLE
[BUG] Criteo 1TB dataset missing

### ISSUE THREAD

**Issue by rllin** [NVIDIA-Merlin/HugeCTR#310]
**Describe the bug**
Is there another source for the criteo data by day?

The links at https://labs.criteo.com/2013/12/download-terabyte-click-logs/ like http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_0.gz seem unavailable.

If there is a mirror, this would be great.  The smaller dataset I found but not the full 1TB.

**Comment by zehuanw** [comment]
Hi @rllin , thank you for your feedback! It's a known issue, we are trying to solve this problem with criteo. We will keep you posted.

**Comment by rllin** [comment]
thanks!  if theres anyway we can help and/or get the dataset privately before it is rehosted, please let us know!

**Comment by rllin** [comment]
@zehuanw do you have any sense of timeline?

**Comment by zehuanw** [comment]
Hi @rllin , sorry that we don't have a clear timeline can be shared. It depend on the response from Criteo. We are keep contacting with them. We will keep you posted.

**Comment by rllin** [comment]
@zehuanw have they been responsive?  we have also tried reaching out to criteo with no responses

**Comment by minseokl** [comment]
Hi @rllin The dataset is available now from Google cloud service. Please check [here](https://ailab.criteo.com/download-criteo-1tb-click-logs-dataset/). We also updated our samples and notebooks accordingly.
Please let me know if it works for you. Thanks!

**Comment by zehuanw** [comment]
Thank you for your feedback! Close the issue.
