### ISSUE TITLE
Error with docker build  

### ISSUE THREAD

**Issue by AtekiRyu** [NVIDIA-Merlin/HugeCTR#311]
When build HugeCTR  with Merlin docker, https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/training/dockerfile.tf
according to this wiki https://nvidia-merlin.github.io/HugeCTR/master/hugectr_contributor_guide.html#set-up-the-development-environment-with-merlin-containers

After make and install, i try to import hugectr in python, an error occurs.

![image](https://user-images.githubusercontent.com/12287905/164448521-fe434770-43e7-4aed-9326-f68a370cb22a.png)

**Comment by zehuanw** [comment]
Hi @AtekiRyu , sorry for late reply. "[dockerfile.tf](https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/training/dockerfile.tf)" is just made for tensorflow users and supported with sok (HugeCTR tf plugin). 
- To use native HugeCTR APIs (import hugectr) you'd better to use https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/training/dockerfile.ctr
- To use sok you may want to follow [these instructions](https://nvidia-merlin.github.io/HugeCTR/master/hugectr_contributor_guide.html#build-sparse-operation-kit-sok-from-source) and `import sparse_operation_kit as sok` 

Please let us know if you have further questions.

**Comment by zehuanw** [comment]
@jershi425 @shijieliu For our [contribution guide](https://nvidia-merlin.github.io/HugeCTR/master/hugectr_contributor_guide.html#set-up-the-development-environment-with-merlin-containers)

- [ ] In the session of `Build HugeCTR from Source` we need to specify that the instructions are only for https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/training/dockerfile.ctr

- [ ] In the session of `https://nvidia-merlin.github.io/HugeCTR/master/hugectr_contributor_guide.html#build-hugectr-from-source` we need to specify that the instructions are only for https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/training/dockerfile.tf

- [ ] We need to add instructions of how to build Inference container.

**Comment by AtekiRyu** [comment]
Thanks, i will try it with your instructions.
