### ISSUE TITLE
[Question]Error with docker

### ISSUE THREAD

**Issue by politefish** [NVIDIA-Merlin/HugeCTR#313]
After building docker using https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/training/dockerfile.ctr and cmake、make install HugeCTR, I cant import HugeCTR in this docker. 
![image](https://user-images.githubusercontent.com/31067539/167356441-7cc0ec1b-d019-44c2-84e2-1e12905b6c1d.png)
What i can do to solve this problem?

**Comment by KingsleyLiu-NV** [comment]
Hi @politefish 
Could you please check `$PYTHONPATH` within the container and ensure that the install path is covered？

**Comment by KingsleyLiu-NV** [comment]
> Hi，thank you for your reply, there is '/usr/local/hugectr/lib' in my PYTHONPATH, is that means make install is finished correctly?

No. Could you please show the log of "make install"?

**Comment by politefish** [comment]
[makeinstall_log.txt](https://github.com/NVIDIA-Merlin/HugeCTR/files/8651180/makeinstall_log.txt)
I make install again and this is the log

**Comment by KingsleyLiu-NV** [comment]
It looks good and could you please check `hugectr.so` exists in the path `/usr/local/hugectr/lib`?

**Comment by KingsleyLiu-NV** [comment]
Can `import hugectr` in the path /usr/local/hugectr/lib?

**Comment by politefish** [comment]
Yes！why？

**Comment by KingsleyLiu-NV** [comment]
`hugectr.so` is the library of the Python module. If you can `import hugectr` in the path `/usr/local/hugectr/lib` AND `/usr/local/hugectr/lib` is in the environment variable `PYTHONPATH`, then there should NOT be any problem of doing `import hugectr` anywhere within the container.

**Comment by politefish** [comment]
![image](https://user-images.githubusercontent.com/31067539/167409607-9ccfd72a-ae4c-45f6-a47e-39c95820dc99.png)
I pasted the wrong picture before, there are the files in /usr/local/hugectr/lib

**Comment by KingsleyLiu-NV** [comment]
> ![image](https://user-images.githubusercontent.com/31067539/167409607-9ccfd72a-ae4c-45f6-a47e-39c95820dc99.png) I pasted the wrong picture before, there are the files in /usr/local/hugectr/lib

@politefish I do not think you are building hugectr Python interface correctly based on this screenshot. It seems that you have mistakenly pass `-DENABLE_INFERENCE=ON` to cmake.
Could you please refer to our contributor guide https://nvidia-merlin.github.io/HugeCTR/master/hugectr_contributor_guide.html#build-hugectr-from-source to get informed of how to build HugeCTR from scratch correctly?

**Comment by KingsleyLiu-NV** [comment]
@politefish Please inform us if you solve the problem.

**Comment by politefish** [comment]
@KingsleyLiu-NV The problem is solved, thank you for your help~
