### ISSUE TITLE
[Question] How can I generate a keyset file from Parquet data.

### ISSUE THREAD

**Issue by Ash-Zheng** [NVIDIA-Merlin/HugeCTR#314]
I have already preprocess my dataset into Parquet file.  And I can successfully run HugeCTR in pure GPU mode. 
When I want to try the **Embedding Trained Cache (ETC)** I met some problem about generating the keyset file. 

How could I generate keyset file from the processed Parquet file?

**Comment by minseokl** [comment]
Hi @Ash-Zheng thanks for reaching out to us. We are actively working on writing a keyset exctraction script and adding a demo on how to use it. It will be included in the upcoming release (22.06). Please let me know if you have more question.s Thanks!

**Comment by Ash-Zheng** [comment]
@minseokl Thanks, I will be waiting for your next release.

**Comment by jershi425** [comment]
Hi @Ash-Zheng, we added a [keyset script](https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/tools/keyset_scripts) and a [ETC demo](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/notebooks/embedding_training_cache_example.ipynb) in our new release. Please take a look and let me know if you have any further questions. Thanks!

**Comment by Ash-Zheng** [comment]
@jershi425 Awesome, thank you!
