### ISSUE TITLE
[Requirement] Adding single GPU SOK test to CI/CD

### ISSUE THREAD

**Issue by zehuanw** [NVIDIA-Merlin/HugeCTR#316]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish HugeCTR could support [...]
We found environment issue of SOK in the NGC container v22.05. 

**Describe the solution you'd like**
After the hot fix, we still need to add some testing to check the basic functions of SOK before release.

**Comment by EmmaQiaoCh** [comment]
Submit changes in this pr: https://github.com/NVIDIA-Merlin/HugeCTR/pull/317

**Comment by EmmaQiaoCh** [comment]
Re-submitted the PR base one the new docker file: https://github.com/NVIDIA-Merlin/Merlin/pull/384
