### ISSUE TITLE
[BUG] notebooks of hugectr_wdl_prediction can not run

### ISSUE THREAD

**Issue by LarryZhangy** [NVIDIA-Merlin/HugeCTR#336]
**Describe the bug**
when i try notebook https://nvidia-merlin.github.io/HugeCTR/master/notebooks/hugectr_wdl_prediction.html
i got error when run preprocess.py 

TypeError: Unsupported type: Cannot convert object of type <class 'method'> to Node.

**To Reproduce**
1. just try notebook

**Expected behavior**
everything is ok.

**Screenshots**
![image](https://user-images.githubusercontent.com/1331144/176814044-437ed263-67df-4d24-a2ef-3a0028d374c4.png)

**Environment (please complete the following information):**
 - OS: ubuntu 16.04
 - Graphic card:  NVIDIA V100
 - CUDA version: CUDA 11.1
 - Docker image : nvcr.io/nvidia/merlin/merlin-training:22.05
 - HugeCTR Version: 3.6

**Comment by jershi425** [comment]
Hi @LarryZhangy, thank you for your feedback. The NV Tabular team is currently working on solving this data preprocessing issue. For now, you are free to try other inference notebooks which uses data generated from our [data generator](https://nvidia-merlin.github.io/HugeCTR/master/api/python_interface.html#data-generator-api), for example, [hps demo](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/notebooks/hps_demo.ipynb).

**Comment by LarryZhangy** [comment]
@jershi425 , Thanks!  I had try it use generated data, it can work.

**Comment by jershi425** [comment]
This issue was fixed in v22.11 release.

**Comment by heroes999** [comment]
I'm afraid it was not correctly fixed in v22.11 @jershi425 

I download nvcr.io/nvidia/merlin/merlin-hugectr    tag  22.11, still get the same error. Any idea to workaround to run wide&deep demo?
