### ISSUE TITLE
[BUG] Failing to run on Windows / WSL 2

### ISSUE THREAD

**Issue by oliverholworthy** [NVIDIA-Merlin/HugeCTR#337]
**Describe the bug**

Running HugeCTR in docker on Windows 11 / WSL 2 results in an exception relating to cpu affinity

**To Reproduce**

1. docker run command (from HugeCTR directory)

```sh
docker run --gpus=all --shm-size=1g --ulimit memlock=-1 -u $(id -u):$(id -g) -it -v $(pwd):/workspace/HugeCTR -w /workspace/HugeCTR nvcr.io/nvidia/merlin/merlin-hugectr:22.06 python test/group_fc_test/dlrm_fp16.py
```

Outputs:

```
HugeCTR Version: 3.7
====================================================Model Init=====================================================
[HCTR][11:53:41.228][INFO][RK0][main]: Initialize model: dlrm
[HCTR][11:53:41.228][WARNING][RK0][main]: MPI was already initialized somewhere elese. Lifetime service disabled.
[HCTR][11:53:41.228][INFO][RK0][main]: Global seed is 994812834
[HCTR][11:53:41.238][INFO][RK0][main]: Device to NUMA mapping:
Traceback (most recent call last):
  File "test/group_fc_test/dlrm_fp16.py", line 23, in <module>
    model = hugectr.Model(solver, reader, optimizer)
RuntimeError: Runtime error: Not Supported
        nvmlDeviceGetCpuAffinity( handle, cpu_mask->size / (sizeof(unsigned long) * 8), cpu_mask->maskp) at init_cpu_mapping(/hugectr/HugeCTR/include/utils.hpp:274)
```

- `cpu_mask->size`  - 256
- `cpu_mask->size / (sizeof(unsigned long) * 8)` - 4

the equivalent call using the python bindings for nvml:

```python
import pynvml
pynvml.nvmlInit()
handle = pynvml.nvmlDeviceGetHandleByIndex(0)
pynvml.nvmlDeviceGetCpuAffinity(handle, 4)
# => Raises NVMLError_NotSupported: Not Supported
```

**Expected behavior**

Construct and run a HugeCTR model (e.g. `test/group_fc_test/dlrm_fp16.py`) without raising an exception.

This may not be an issue with HugeCTR itself. Since this error is raised by nvml provided a cpu set size of 4. However, any advice you can provide would be helpful.

**Environment (please complete the following information):**

Running Ubuntu on Windows 11 with WSL 2.

 - OS: Ubuntu 20.04 LTS (WSL 2)
 - Graphic card: NVIDIA RTX A3000 Laptop GPU
 - CUDA version: 11.7
 - Docker image: `nvcr.io/nvidia/merlin/merlin-hugectr:22.06`

**Comment by KingsleyLiu-NV** [comment]
@oliverholworthy Thanks for the feedback. If you refer to the document of NVML APIs, you can find that `nvmlDeviceGetCpuAffinity` is **supported on Linux only**.  For more details, please see https://docs.nvidia.com/deploy/nvml-api/group__nvmlAffinity.html#group__nvmlAffinity.

**Comment by MustaphaU** [comment]
Is there any workaround for this limitation on WSL 2?

```error
RuntimeError: Runtime error: Not Supported
	nvmlDeviceGetCpuAffinity( handle, cpu_mask->size / (sizeof(unsigned long) * 8), cpu_mask->maskp) (init_cpu_mapping @ /workdir/HugeCTR/include/utils.hpp:282)
```

**Comment by KingsleyLiu-NV** [comment]
@MustaphaU As of now, NVML does not have full support on WSL 2, especially for low-level hardware queries and APIs like nvmlDeviceGetCpuAffinity. This limitation is due to how WSL 2 works: it adds virtualization and abstraction layers between the Windows host and the Linux guest environment, preventing NVML from directly accessing hardware topology details.

There is currently no known general workaround or hack to make these NVML APIs fully functional in WSL 2. Some basic NVML functions (like nvidia-smi) work with limited capability, but more advanced features—especially those dealing with GPU topology and CPU affinity—will either fail, return "not supported," or provide incomplete data.
