### ISSUE TITLE
[Question] Failed to preprocess criteo data

### ISSUE THREAD

**Issue by LarryZhangy** [NVIDIA-Merlin/HugeCTR#338]
when i try to run a sample of wdl  https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/samples/wdl
i got a error at step :Preprocess the Dataset Through NVTabular 

bash preprocess.sh 0 criteo_data nvt 1 0 1 # parquet output

error : 
![image](https://user-images.githubusercontent.com/1331144/177236714-6e582482-7a21-488a-849d-b978c562c144.png)

**Comment by jershi425** [comment]
Hi @LarryZhangy, NVTabular has updated the API and we are working on fixing the data preprocessing scripts to make them work. I will let you know once we fixed it.

**Comment by LarryZhangy** [comment]
@jershi425 , when this bug can be fixed?

**Comment by Spidey0918** [comment]
I run the preprocessing script and got an IndexError, not quite sure what it means. Can anyone enlight me on this?
![image](https://user-images.githubusercontent.com/65277376/200902231-55614999-e315-4bc9-b88a-349300d1004b.png)

**Comment by jershi425** [comment]
This issue was fixed in v22.11 release.
