### ISSUE TITLE
[Question] Complete guide to train wdl model using all 1TB criteo data  in only six minutes

### ISSUE THREAD

**Issue by LarryZhangy** [NVIDIA-Merlin/HugeCTR#339]
I know the performance of HugeCTR +  NVTabular is awesome, the Criteo 1TB Click Logs Dataset can be processed and a full model can be trained in only six minutes.

> When running NVTabular on the Criteo 1TB Click Logs Dataset using a single V100 32GB GPU, feature engineering and preprocessing was able to be completed in 13 minutes. Furthermore, when running NVTabular on a DGX-1 cluster with eight V100 GPUs, feature engineering and preprocessing was able to be completed within three minutes. Combined with [HugeCTR](http://www.github.com/NVIDIA/HugeCTR/), the dataset can be processed and a full model can be trained in only six minutes.

But when i try to reproduct it, i got same problem:
#338 #336 #332 

So, can HugeCTR group write a complete notebook to guide how to process and train wdl model useing 1TB criteo data  in only six minutes?

Thank you!

**Comment by jershi425** [comment]
This preprocessing script issue has been fixed and the affected notebooks are now able to run without problem. Please feel free to try them, thanks!
