### ISSUE TITLE
when cache_size_ >1  the train loss is zero 

### ISSUE THREAD

**Issue by BookChan** [NVIDIA-Merlin/HugeCTR#34]
We find that  setting  cache_size_ >1 in DataCollector ,  the train loss is almost zero .  In  DataCollector.hpp :

```c++
template <typename TypeKey>
void DataCollector<TypeKey>::collect() {
  if (counter_ < cache_size_ || cache_size_ == 0) {
    collect_();
  } else {
    collect_blank_(); 
  }
}
```
counter_  is increment , and will never less than cache_size_  once it's bigger than cache_size_ . And not collect is running, so the train data is old version , and model is overfit , loss is almost zero .
The correct code  is supposed to be 
```c++
template <typename TypeKey>
void DataCollector<TypeKey>::collect() {
  if (counter_ % internal_buffers_.size() < cache_size_ || cache_size_ == 0) {
    collect_();
  } else {
    collect_blank_(); 
  }
}
```

**Comment by KingsleyLiu-NV** [comment]
cache_size must be only valid for the evaluation data reader, i.e., if cache_eval_data is false or the data reader and its collector is for training, cache_size_ is set to 0.

**Comment by zehuanw** [comment]
Hi @BookChan , thank you for your feedback! We are closing this issue. If @KingsleyLiu-NV 's reply doesn't solve your problem, please reopen it.
