### ISSUE TITLE
[BUG] Compilation of 'dlrm_raw' failed with error "Cannot determine link language for target "dlrm_raw"

### ISSUE THREAD

**Issue by avinashc27** [NVIDIA-Merlin/HugeCTR#345]
**Describe the bug**
'dlrm_raw' tool under https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/tools/dlrm_script/ is failed to build using Cmake.

**To Reproduce**
1. base container: nvcr.io/nvidia/merlin/merlin-tensorflow-training:22.05
2. cd /workspace/HugeCTR/tools/dlrm_script
3. cmake .

**Expected behavior**
build dlrm_raw binary

**Output**
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error: Cannot determine link language for target "dlrm_raw".
CMake Error: CMake can not determine linker language for target: dlrm_raw
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

![image](https://user-images.githubusercontent.com/107385648/180957224-40e18ea0-6ce3-437d-a9d3-19f81d65f10c.png)

**Environment (please complete the following information):**
 - Docker image : merlin-tensorflow-training:22.05
 - cmake version: 3.23.2

**Attempt to resolve**
I have manually added "set_target_properties(dlrm_raw PROPERTIES LINKER_LANGAUGE CXX)" to CMakeLists,txt  at line 41, still same errors even after removing cmake cache files.

**Comment by JacoCheung** [comment]
Hi @avinashc27, do you only need to compile the tools/dlrm_script ? it turns out that the `tools` (And its children folders) is not an independent **project** or a library. It's just a componet of HugeCTR project and depends on other componets of the HugeCTR.  Neither `project()` command nor languages can be specifiled in tool/CMakeLists.txt and you can not just execute `cmake` under this folder. The correct entry of  building the `tool` is from outside. 

If you really want to compile standalone tools/dlrm_script , you need to properly modify the CMakeLists.txt (Languages, include path & dependent library). Below is a modified file example: 

```
cmake_minimum_required(VERSION 3.16)

# specify the correct LANGUAGES
project(hctr_tools_dlrm LANGUAGES CXX CUDA)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CUDA_STANDARD 17)

# find required lib
find_package(CUDA REQUIRED)

file(GLOB dlrm_raw_src
  ${PROJECT_SOURCE_DIR}/../../HugeCTR/src/base/debug/logger.cpp
  dlrm_raw.cu
)

set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Wno-deprecated-declarations")
set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} --expt-extended-lambda --expt-relaxed-constexpr")

set(CONDA_PREFIX /opt/conda)

# add proper include directories 
include_directories(${CONDA_PREFIX}/include)
include_directories(${PROJECT_SOURCE_DIR}/tools/dlrm_script)
include_directories(${PROJECT_SOURCE_DIR}/third_party/cub)
include_directories(${CONDA_PREFIX}/include/libcudf/libcudacxx)
include_directories(
  ${PROJECT_SOURCE_DIR}/
  ${PROJECT_SOURCE_DIR}/../
  ${PROJECT_SOURCE_DIR}/../../
  ${PROJECT_SOURCE_DIR}/../../HugeCTR/include
  $ENV{CONDA_PREFIX}/include
  $ENV{CONDA_PREFIX}/include/libcudf/libcudacxx
  ${CUDA_INCLUDE_DIRS}
)

link_directories(${CONDA_PREFIX}/lib)

add_executable(dlrm_raw ${dlrm_raw_src})

if(MPI_FOUND)
  target_link_libraries(dlrm_raw PUBLIC cudart cudf ${MPI_CXX_LIBRARIES})
else()
  target_link_libraries(dlrm_raw PUBLIC cudart cudf)
endif()
set_target_properties(dlrm_raw PROPERTIES CUDA_RESOLVE_DEVICE_SYMBOLS ON)
set_target_properties(dlrm_raw PROPERTIES CUDA_ARCHITECTURES OFF)
target_compile_features(dlrm_raw PUBLIC cxx_std_17)
```

**Comment by avinashc27** [comment]
Thanks @JacoCheung , Modified CMakeLists.txt you shared did the job..
