### ISSUE TITLE
Fail to build docker image with ENABLE_MULTINODES=ON

### ISSUE THREAD

**Issue by ShawnXuan** [NVIDIA-Merlin/HugeCTR#35]
Here is the command
```
docker build --build-arg ENABLE_MULTINODES=ON -t hugectr:devel -f ./tools/dockerfiles/build.Dockerfile .
```
and got errors below:
```
In file included from /HugeCTR/HugeCTR/include/gpu_resource.hpp:19:0,
                 from /HugeCTR/HugeCTR/src/gpu_resource.cpp:17:
/HugeCTR/HugeCTR/include/common.hpp:29:10: fatal error: mpi.h: No such file or directory
 #include <mpi.h>
          ^~~~~~~
compilation terminated.
```

I think the [dockerfile](https://github.com/NVIDIA/HugeCTR/blob/master/tools/dockerfiles/dev.Dockerfile) does not meet the requirements of multi-nodes.

**Comment by KingsleyLiu-NV** [comment]
The `./tools/dockerfiles/build.Dockerfile` does not provide the packages related to MPI. Please refer to `dev.a100.Dockerfile` to build with Multi-Nodes Training Supported.

**Comment by bashimao** [comment]
Closing. This issue is confirmed as being resolved in the current version and actively monitored in our CI to ensure it cannot happen again.
