### ISSUE TITLE
Maybe there is a typo in API docs? 

### ISSUE THREAD

**Issue by MARD1NO** [NVIDIA-Merlin/HugeCTR#358]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/42901638/187857839-3ae5c7d2-6b67-442a-bb22-c8d60d05dc76.png">

Maybe the description of dropout_rate is wrong? Set 1.0 indicates dropout all the elements, set 0.0 do not dropout.

**Comment by bashimao** [comment]
Agree. The general understanding of dropout is that the rate is the probability `p` of a value to be dropped. So software should behave like this and the description should be accordingly. Can we confirm that the layer works accordingly + change the description?

Hence,
- `p = 1` dropout all elements.
- `p = 0` dropout no elemnts.

**Comment by minseokl** [comment]
Thanks for your feedback. We pushed the change into our master branch. Thanks.
