### ISSUE TITLE
No reaction appeared after the training start

### ISSUE THREAD

**Issue by ZacheryAU** [NVIDIA-Merlin/HugeCTR#36]
Hi professionals, 
We tried the steps in the HugeCTR tutorial and picked DeepFM for trail and successfully started the training, but nothing happened after the 'HugeCTR training start' text (we had waited for several days). 

We tried several network configs, which however focusing on the max_iter meaning that network architecture was not changed, same problem.

System: Ubuntu 18.04.4 LTS
GPU: GeForce RTX 2080 Ti
Driver Version: 440.44
CUDA Version: 10.2

**Comment by chirayuG-nvidia** [comment]
Hi, can you please set "display": to 1 in solver parameters in the config file and check if anything is printed. Please ensure you enable "SM 75" when compiling HugeCTR, to work on RTX 2080 Ti.

**Comment by ZacheryAU** [comment]
> Hi, can you please set "display": to 1 in solver parameters in the config file and check if anything is printed. Please ensure you enable "SM 75" when compiling HugeCTR, to work on RTX 2080 Ti.

still freezes on 'HugeCTR training start'

**Comment by chirayuG-nvidia** [comment]
Thank you for trying, can you please build HugeCTR with debug flags and share entire log printed on screen when you start training.
`cmake -DCMAKE_BUILD_TYPE=Debug -DSM=75 ..`

**Comment by ZacheryAU** [comment]
> Thank you for trying, can you please build HugeCTR with debug flags and share entire log printed on screen when you start training.
> `cmake -DCMAKE_BUILD_TYPE=Debug -DSM=75 ..`

Nothing appeared on the screen after 'HugeCTR training start'.
More information, we skipped the 'build' folder making and directly cmake, and trimmed the size of criteo dataset with python pandas because of our limited RAM. Not sure whether they matter.

**Comment by zehuanw** [comment]
I think DeepFM sample should not consume too much memory and if memory allocation failed it will throw exception. We just release our docker container on NGC: https://ngc.nvidia.com/catalog/containers/nvidia:hugectr. Would you like to have a try? It will help you if you have problem of environments.

**Comment by ZacheryAU** [comment]
I installed newer HugeCTR from GitHub and the problem is solved. Thank you for your attention. 

> I think DeepFM sample should not consume too much memory and if memory allocation failed it will throw exception. We just release our docker container on NGC: https://ngc.nvidia.com/catalog/containers/nvidia:hugectr. Would you like to have a try? It will help you if you have problem of environments.

Could you please provide more guidance for this NGC docker container for the people who want to try it?

**Comment by zehuanw** [comment]
Thank you for your feedback! Please find the guidance on https://github.com/NVIDIA-Merlin/HugeCTR#getting-started. I would like to close this issue but please let us know if you still encounter problems.
