### ISSUE TITLE
[BUG] Criteo example fail due to "Runtime error: file list open failed: ./criteo_data/file_list.txt"

### ISSUE THREAD

**Issue by thuningxu** [NVIDIA-Merlin/HugeCTR#360]
**Describe the bug**
Criteo example fails because file_list.txt is missing

**To Reproduce**
1. Follow the step https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/samples/criteo, running directly the docker image `nvcr.io/nvidia/merlin/merlin-hugectr:22.07`
2. Download and preprocess data using NVTabular
3. python3 ../samples/criteo/criteo.py

**Expected behavior**
Model trains

**Screenshots**
<img width="923" alt="image" src="https://user-images.githubusercontent.com/6064218/189732210-be91a07c-3f02-4ceb-a605-6085be5d75bc.png">

**Environment (please complete the following information):**
 - OS: # uname -a
Linux gke-us-central1-v3-t4x1-prod-v1-4a179b1d-l59w 5.4.188+ #1 SMP Tue May 24 10:06:08 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Graphic card: T4
 - CUDA version: NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.7
 - merlin-hugectr:22.07

**Additional context**

**Comment by thuningxu** [comment]
Preprocessing with `perl` does not have this problem. Seems `nvt` has some difference here.

**Comment by JacoCheung** [comment]
@thuningxu could you please confirm the `./criteo_data/file_list.txt` does exist? If there's no such file or the file is in wrong directory, the preprocessing may accout for it, otherwise the data reader may be buggy.

**Comment by JacoCheung** [comment]
Hi @thuningxu , do you still have this problem in the latest release?
