### ISSUE TITLE
[Question]DIN sample slot_size_array and key range overlap

### ISSUE THREAD

**Issue by liguo88** [NVIDIA-Merlin/HugeCTR#366]
DIN example link: https://github.com/NVIDIA-Merlin/HugeCTR/blob/main/samples/din/din_parquet.py

1. In this example, we have this code: 
`reader = hugectr.DataReaderParams(
    data_reader_type=hugectr.DataReaderType_t.Parquet,
    source=["./din_data/train/_file_list.txt"],
    eval_source="./din_data/valid/_file_list.txt",
    check_type=hugectr.Check_t.Non,
    num_workers=1,
    slot_size_array=[
        192403,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        63001,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        801,
    ],
)`

From the document (https://nvidia-merlin.github.io/HugeCTR/master/api/python_interface.html#), I found this to describe slot_size_arry: 
> We provide an option to add offset for each slot by specifying slot_size_array. slot_size_array is an array whose length is equal to the number of slots. To avoid duplicate keys after adding offset, we need to ensure that the key range of the i-th slot is between 0 and slot_size_array[i]. We will do the offset in this way: for i-th slot key, we add it with offset slot_size_array[0] + slot_size_array[1] + … + slot_size_array[i - 1].

**If I understand correctly, the first slot key range is from [0, 192403), the 2nd to 12th slot will start from 192403 since their slot_size=0. Which means they will have the same key range for these slots to make sure they have the same one-hot encoding space, since they are sequential and should be in the same embedding sapce.** But in the document (https://nvidia-merlin.github.io/HugeCTR/master/api/python_interface.html#) also states:

> The input keys for categorical are distributed to the slots with no overlap allowed. For example: slot[0] = {0,10,32,45}, slot[1] = {1,2,5,67}. If there is any overlap, it will cause an undefined behavior. For example, given slot[0] = {0,10,32,45}, slot[1] = {1,10,5,67}, the table looking up the 10 key will produce different results based on how the slots are assigned to the GPUs.

**Are they conflicting for this DIN example since slot 2 to slot 12 have the same key ranges?**

**If my understanding is not correct, could you explain why we put 0s for some of slots for DIN sample?** 

2. For this code 
   `model.add(
    hugectr.Input(
        label_dim=1,
        label_name="label",
        dense_dim=0,
        dense_name="dense",
        data_reader_sparse_param_array=[
            hugectr.DataReaderSparseParam("UserID", 1, True, 1),
            hugectr.DataReaderSparseParam("GoodID", 1, True, 11),
            hugectr.DataReaderSparseParam("CateID", 1, True, 11),
        ],
    )
)`
**Does "hugectr.DataReaderSparseParam("GoodID", 1, True, 11)" mean all products embedding using the same space? Like for same integer in different slots under "GoodID" will have the same embeddings.**

**Comment by yingcanw** [comment]
Thanks for the feedback, because the DIN model is a recommendation model that supports sequence data, that is, the sequence data represents the user's history info, for example, the GoodID here is the user's browsing items within a period of time, then all items belong to the same embedding space and can also be repeated(overlap).

**Comment by JacoCheung** [comment]
Hi @liguo88 , sorry for the confusing. Let me elaborate it. This is actually a hack on `sequence data input`. Actually a non-zero key and the following continuous zeros **share the same embedding space** as you said, which means that **slot 2 to slot 12 have the same key ranges**. They are in the same embedding space, and thus there should be no overlap. 
The overlap issue occurs if two slots are in different embeddings but in the same key range. 
We will keep simplifying the configuration, you can regard this as a WAR. Thanks for your question!
