### ISSUE TITLE
[Question] How to correctly use Embedding Training Cache feature in HugeCTR

### ISSUE THREAD

**Issue by yuqie** [NVIDIA-Merlin/HugeCTR#373]
Hi, I tried to use ETC feature to train a model with embedding size of several hundred GB. And found the required GPU and CPU memory with ETC staged are greater than the case without ETC. 
The etc_sample.py (https://nvidia-merlin.github.io/HugeCTR/main/notebooks/embedding_training_cache_example.html) is used as an template, only the ETC type is changed to staged and the dataset changed to what I used (vocabulary size is around a billion and the embedding table size is around 80G). When conducted on a server with 8x80G A100, the GPU memory footprint has almost 10 GB difference, and there are ~350GB additional CPU memory occupied, which means the memory required for ETC is larger than that without ETC.  
The question is how to estimate the CPU memory consumed, are there any formula between CPU memory and embedding table size.
Besides, what is the  correct way to train models with huge embedding tables size that exceed the available GPU memory by using ETC. In my case, could I train  a model with embedding tables size larger than 640G using a server with 8x80G A100 and ~1T CPU memory?

**Comment by zehuanw** [comment]
Thank you for your interest in HugeCTR and ETC.

The ETC has the following overhead in temrs of GPU and memory capacities:
•	The extra GPU memory consumption is attributed to the key buffer. It is filled from a input keyset file, and used to load and dump the GPU embedding table. Its size in total should be # unique keys per pass * sizeof(key)
•	The 350GB CPU memory consumption is a little bit unclear. If you are using "Staged-PS", which loads the entire embedding table into the CPU memory from the storage, CPU memory consumption can be greater than your embedding table size. If you want to mitigate the overhead, consider using "Cached-PS". But you mentioned your Embedding table size is 80GB It sounds much smaller than 350GB. Can you confirm that 80GB is the entire Embedding table size (sum of all the table on all GPUs)?

> In my case, could I train a model with embedding tables size larger than 640G using a server with 8x80G A100 and ~1T CPU memory

It should be possible, but may need SSD usage and 1TB CPU memory is not enough, if you are using some optimizer with momentum. e.g. Adam has 3x memory consumption than SGD (for your case it will be 3x640GB).

For more information, please checkout out [the related section](https://nvidia-merlin.github.io/HugeCTR/master/hugectr_embedding_training_cache.html#parameter-server-in-etc) in our ETC documentaiton.

Note that we are going to deprecated ETC and leverage [HKV](https://github.com/NVIDIA-Merlin/HierarchicalKV) 
on the training with hierarchical memory.
