### ISSUE TITLE
[Question] how to not use cuda graph in hugectr?

### ISSUE THREAD

**Issue by LucQueen** [NVIDIA-Merlin/HugeCTR#374]
how to not use cuda graph in hugectr?

my command is like

huge_ctr --train config.json

and i add use_cuda_graph:false in config.json, but still use cuda_graph when i train.

{
  "solver": {
    "lr_policy": "fixed",
    "display": 1000,
    "max_iter": 75868,
    "gpu": [0,1,2,3,4,5,6,7],
    "batchsize": 55296,
    "batchsize_eval": 1769472,
    "eval_batches": 51,
    "snapshot": 10000000,
    "snapshot_prefix": "./",
    "eval_interval": 3793,
    "mixed_precision": 1024,
    "eval_metrics": ["AUC:0.8025"],
    "enable_overlap": true,
    "holistic_cuda_graph": false,
    "use_cuda_graph": false
  },

**Comment by shijieliu** [comment]
hi @LucQueen which version of HugeCTR are you using?

**Comment by LucQueen** [comment]
@shijieliu i am using 3.1
