### ISSUE TITLE
[BUG] Documentation for Optimizer types has a typo.

### ISSUE THREAD

**Issue by ashish007git** [NVIDIA-Merlin/HugeCTR#377]
**Describe the bug**
There seems to be a typo for Adagrad  optimizer type in documentation. The type should be listed as `hugectr.Optimizer_t.AdaGrad` instead of `hugectr.Optimizer_t.Adagard`. 

**To Reproduce**
https://nvidia-merlin.github.io/HugeCTR/master/api/python_interface.html#createoptimizer-method

**Screenshots**
![image](https://user-images.githubusercontent.com/14234526/218896943-760e3957-b817-4038-a75f-116491d026ea.png)

**Comment by WonderingWJ** [comment]
@ashish007git Thank you  for your report! we will fix it in the next realease.

**Comment by WonderingWJ** [comment]
The issue is fixed
