### ISSUE TITLE
[Question]  How to get the performance of inference

### ISSUE THREAD

**Issue by liangxuegang** [NVIDIA-Merlin/HugeCTR#379]
Hi, how can I get the performance of inference in HugeCTR? I want to get the time of host2device, device2host and  model run

**Comment by jershi425** [comment]
@liangxuegang Thanks for the question. For inference performance, please refer to the [HPS profiler](https://github.com/NVIDIA-Merlin/HugeCTR/blob/main/HugeCTR/src/inference_benchmark/hps_profiler.md).

**Comment by liangxuegang** [comment]
Thanks for responding, I will have a try
