### ISSUE TITLE
[BUG] EmbeddingCollection Wgrad buffer sizes can overflow a 32 bit integer.

### ISSUE THREAD

**Issue by zpzim** [NVIDIA-Merlin/HugeCTR#382]
**Describe the bug**

Because `max_buffer_size` is stored as a 32-bit integer in the following code snippet:
https://github.com/NVIDIA-Merlin/HugeCTR/blob/772fd505e3652ce143be2ee83f025dc36cf16e89/HugeCTR/embedding/common.cpp#L386-L399

It can easily lead to an overflow of the value when the batch size is large. This can result in a negative value being passed to the HugeCTR memory allocator, which gets interpreted as an unsigned integer by cudaMalloc, instantly triggering an OOM.

**Expected behavior**
This value should be stored as a 64-bit integer.

**Comment by zpzim** [comment]
Actually this same issue is present for the AllreduceWgradInitializer::init_data() method.

https://github.com/NVIDIA-Merlin/HugeCTR/blob/772fd505e3652ce143be2ee83f025dc36cf16e89/HugeCTR/embedding/common.cpp#L496

**Comment by shijieliu** [comment]
Thanks for the feedback! We will check and fix it.

**Comment by RayWang96** [comment]
The fix is in the main branch, @zpzim could you verify it? Thanks.
