### ISSUE TITLE
[Question] negative item counts in MovieLens notebook 

### ISSUE THREAD

**Issue by JohnFirth** [NVIDIA-Merlin/HugeCTR#384]
Hey, can you explain the choices of 500 and 100 negative items per user for the train and test sets here https://github.com/NVIDIA-Merlin/HugeCTR/blob/main/notebooks/movie-lens-example.ipynb ?

Thanks!

**Comment by jershi425** [comment]
Hi @JohnFirth , thanks for the question. The negative items per user for train and test sets are chosen arbitrarily.
