### ISSUE TITLE
[Question] SOK - How to save sok.expertiment.Variable correctly into saved model ?

### ISSUE THREAD

**Issue by Nov11** [NVIDIA-Merlin/HugeCTR#388]
As sok.expertiment is not compatible with tensorflow distribute strategy, I' m trying to use it with Horovod.
When conducting parallel training with 2 process like 'horovodrun -np 2 xxxx', I suppose each sok.experiment.DistributeVarible in the 2 process hold 1 / 2 of the weight.
Say I have [[0], [1], [2], [3]] for a sok distribute variable, process 0 holds [[0], [2]], process 1 holds [[1], [3]].

Question is how to save them into tensorflow saved_model and load them correctly?

If 'save' is called on rank0, weight on process 1 will be missing.
If 'save' is called on rank0 and rank1, weight not created by sok.experiment will be duplicated.

Maybe there's a way to call 'save' on rank0 and write all the weights of the variable from rank0~n to the saved model?

Here is the code:
```python 
import tensorflow._api.v2.compat.v1 as tf

tf.disable_eager_execution()

import horovod.tensorflow as hvd
from sparse_operation_kit import experiment as sok
from tensorflow.keras import initializers

import os

os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'


def setup():
    hvd.init()
    gpus = tf.config.experimental.list_physical_devices("GPU")
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)
    if gpus:
        tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], "GPU")  # nopep8

    sok.init()


setup()


class CustomInit(initializers.Initializer):

    def __call__(self, shape, dtype=None, **kwargs):
        return tf.reshape(tf.range(tf.reduce_prod(shape), dtype=tf.float32), shape)


class SimpleModel(tf.keras.models.Model):
    def __init__(self) -> None:
        super().__init__()
        self.dense = tf.keras.layers.Dense(5, kernel_initializer=CustomInit())
        self.dense.build([None, 2])
        self.sok_var = sok.Variable(initial_value=CustomInit()([16, 3]))

    def show_weights(self, sess):
        print('dense', sess.run(model.dense.kernel))
        print('sok_var', sess.run(model.sok_var))

    def minus_one(self, sess):
        sess.run(tf.assign(self.dense.kernel, tf.add(self.dense.kernel, -1)))
        sess.run(tf.assign(self.sok_var, tf.add(self.sok_var, -1)))


model = SimpleModel()

saved_model_path = 'tmp/simple_model'


def do_save():
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        model.minus_one(sess)
        model.show_weights(sess)

        saver = tf.train.Saver()
        saver.save(sess, saved_model_path)


def do_restore():
    with tf.Session() as sess:
        saver = tf.train.Saver()
        saver.restore(sess, saved_model_path)

        model.show_weights(sess)


if __name__ == "__main__":
    # horovod suggests save checkpoint in process of rank 0
    # but this saves only the weight on process 0, without that on process 1.
    # if hvd.rank() == 0:
    #    do_save()
    do_restore()
```

**Comment by kanghui0204** [comment]
Hi @Nov11 ，SOK dump and load still need optimizer state dump and load ，so this function we don't release. you use the SOK.variable is a static variable , and distribute average in every gpu, just like this：
you run on 3 gpus , you SOK variable shape is [10,4],that means have 10 embedding vectors ,and each gpu take the embedding index as below:
gpu0 0 3 6 9 
gpu1 1 4 7 
gpu2 2 5 8

and SOK.variable is a tensorflow variable , so you can save every gpu's variables as save tf variables,and concat them. If we release the SOK.dump(variables , optimizer) or SOK.load(variables , optimizer)  , you can use thoes api replace the method I mentioned.

**Comment by Nov11** [comment]
Got it ! 
Thank you.
