### ISSUE TITLE
[Question] Does ETC training feature support to run on multiple physical nodes?

### ISSUE THREAD

**Issue by zpcalan** [NVIDIA-Merlin/HugeCTR#390]
Hi, developers of HugeCTR. Does ETC training feature support to run on multiple physical nodes?
For example:
A remote node only has CPU chips but has large capacity SSD. So I want to deploy [Cached-PS ](https://nvidia-merlin.github.io/HugeCTR/main/hugectr_embedding_training_cache.html#cached-host-memory-parameter-server) on this node while using another node with GPU to do training.

It does not seem to be mentioned in the document that multiple nodes' ETC is supported but I'm not sure.
Thank you very much!

**Comment by minseokl** [comment]
Hi zpcalan, the ETC supports multi-node environments as well. However, it can not be used in a way you describe, e.g., CPU-only node-0 and GPU equipped node-1. The ETC assumes that all nodes are GPU nodes.
By the way, we are considering to deprecate the ETC but replace it with [HierarchicalKV](https://github.com/NVIDIA-Merlin/HierarchicalKV). Please check the repo if you are interested in it. Thanks!
