### ISSUE TITLE
[Question]How to process criteo day0(50GB)'s dataset to run ETC?

### ISSUE THREAD

**Issue by zpcalan** [NVIDIA-Merlin/HugeCTR#397]
Hi, developers of HugeCTR. 
Lately I've been working on testing ETC. So there maybe some questions about its usage. Thanks for taking time out of your busy schedule to answer my questions!

I'm running wdl training with ETC according to [ETC example](https://nvidia-merlin.github.io/HugeCTR/main/notebooks/embedding_training_cache_example.html) and I also read this ETC [doc](https://nvidia-merlin.github.io/HugeCTR/main/hugectr_embedding_training_cache.html) carefully but I still got some questions when running large dataset(criteo day0 data which is about 50GB).

After I preprocessing dataset as [this](https://github.com/NVIDIA-Merlin/HugeCTR/tree/main/samples/wdl#preprocess-the-dataset-through-nvtabular) , I generate 20 parquet data files. Then I generate keyset file as [this](https://nvidia-merlin.github.io/HugeCTR/main/hugectr_embedding_training_cache.html#preprocessing) ETC doc suggests. Files are shown below.
```
-rw-r--r-- 1 root root  993 Apr 26 08:15 _file_list.txt
-rw-r--r-- 1 root root  46M Apr 27 08:19 _hugectr.keyset
-rw-r--r-- 1 root root 9.8M Apr 26 08:15 _metadata
-rw-r--r-- 1 root root 2.5K Apr 26 08:15 _metadata.json
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_0.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_1.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_10.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_11.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_12.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_13.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_14.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_15.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_16.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_17.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_18.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_19.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_2.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_3.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_4.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_5.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_6.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_7.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_8.parquet
-rw-r--r-- 1 root root 635M Apr 26 08:15 part_9.parquet
-rw-r--r-- 1 root root  28K Apr 26 08:12 schema.pbtxt
drwxr-xr-x 2 root root 4.0K Apr 26 08:08 temp-parquet-after-conversion/
-rw-r--r-- 1 root root  38G Apr 26 08:05 train.txt
```
As you can see, there's only one `_file_list.txt` and one keyset file. 
When I run wdl ETC with this configuration:
```
reader = hugectr.DataReaderParams(
    data_reader_type=hugectr.DataReaderType_t.Parquet,
    source=["./etc_data/day0/train/_file_list.txt"],
    keyset = ["./etc_data/day0/train/_hugectr.keyset"],
    slot_size_array=[897291, 1057226, 803619, 24566, 14910, 7184, 19506, 4, 6453, 1271, 55, 678840, 166794, 121408, 11, 2201, 8825, 63, 4, 953, 15, 809329, 438642, 769014, 128698, 10118, 82, 34],
    eval_source="./etc_data/day0/val/_file_list.txt",
    check_type=hugectr.Check_t.Non,
)

hc_cnfg = hugectr.CreateHMemCache(num_blocks = 8, target_hit_rate = 0.8, max_num_evict = 10)
etc = hugectr.CreateETC(ps_types = [hugectr.TrainPSType_t.Cached, hugectr.TrainPSType_t.Cached],
                       sparse_models = ["./wdl_wide_model", "./wdl_deep_model"],
                       local_paths = ["./"], hmem_cache_configs = [hc_cnfg])
model.add(
    hugectr.SparseEmbedding(
        embedding_type=hugectr.Embedding_t.DistributedSlotSparseEmbeddingHash,
        workspace_size_per_gpu_in_mb=69,
        embedding_vec_size=1,
        combiner="sum",
        sparse_embedding_name="sparse_embedding2",
        bottom_name="wide_data",
        optimizer=optimizer,
    )
)
model.add(
    hugectr.SparseEmbedding(
        embedding_type=hugectr.Embedding_t.LocalizedSlotSparseEmbeddingHash,
        workspace_size_per_gpu_in_mb=10240,
        embedding_vec_size=240,
        combiner="sum",
        sparse_embedding_name="sparse_embedding1",
        bottom_name="deep_data",
        optimizer=optimizer,
    )
)
```
I set workspace_size_per_gpu_in_mb to 10GB, but there's still `memory not enough` error thrown:

```
[HCTR][08:58:05.426][INFO][RK0][main]: HMEM-Cache PS: Hit rate [load]: 0 %
[HCTR][08:58:05.558][INFO][RK0][main]: HMEM-Cache PS: Hit rate [load]: 0 %
[HCTR][08:58:21.489][INFO][RK0][main]: Iter: 200 Time(200 iters): 16.3905s Loss: 0.140545 lr:0.001
[HCTR][08:58:37.228][INFO][RK0][main]: Iter: 400 Time(200 iters): 15.6937s Loss: 0.132971 lr:0.001
[HCTR][08:58:52.973][INFO][RK0][main]: Iter: 600 Time(200 iters): 15.6988s Loss: 0.131649 lr:0.001
[HCTR][08:59:08.742][INFO][RK0][main]: Iter: 800 Time(200 iters): 15.7229s Loss: 0.129974 lr:0.001
[HCTR][08:59:17.338][ERROR][RK0][main]: Check Failed!
        File: /hugectr/HugeCTR/include/embeddings/localized_slot_sparse_embedding_hash.hpp:558
        Function: check_overflow
        Expression: count <= max_vocabulary_size_per_gpu_
        Hint: Runtime vocabulary size 3729654 exceeds max_vocabulary_size_per_gpu 3728270 on GPU 7. new feature insertion failed. Please adjust workspace_size_per_gpu according to https://nvidia-merlin.github.io/HugeCTR/master/QAList.html#how-to-set-workspace-size-per-gpu-in-mb-and-slot-size-array. How to set workspace_size_per_gpu_in_mb and slot_size_array
```

Even though I increase `workspace_size_per_gpu_in_mb`, the error remains. I think it's may because it uses all keys in keyset file, which are day0's all catagorical features. It must be too many for single GPU card's memory. I don't know why it can not trigger ETC's eviction feature so that new feature could be loaded. Is it because there's only one `_file_list.txt` and one keyset file?

As [this link](https://nvidia-merlin.github.io/HugeCTR/main/hugectr_embedding_training_cache.html#feature-description) describes, such a large dataset(day0) should be split into multiple dataset files. But how can I split day0's dataset to multiple datasets and multiple keyset files? The examples only generate one `_file_list.txt` and only one keyset file could be generated.

**Comment by JacoCheung** [comment]
Hi @zpcalan , If I understand correctly, you already have preprocessed part_[0,9].parquet file + single keyset file. To get multiple keyset file , you can try our [keyset extractor tool](https://github.com/NVIDIA-Merlin/HugeCTR/tree/main/tools/keyset_scripts). You can split the 10 parquet files into N groups ($N<10$) , and each group is a folder that has a file_list.txt, *.parquet . By doing so, you can extract a keyset file for each group.  (Don't forget to add the `slot_size_array`argument when using the tool)

**Comment by zpcalan** [comment]
@JacoCheung Thanks.
I moved my parquet files to multiple folders and manually create _file_list.txt for each folder. After using keyset tool, key set files could be generated under each folder as you say.
But how to set my slot_size_array. I generated keyset file using slot_size_array which is printed in the process of day0's data processing, which is `[897291, 1057226, 803619, 24566, 14910, 7184, 19506, 4, 6453, 1271, 55, 678840, 166794, 121408, 11, 2201, 8825, 63, 4, 953, 15, 809329, 438642, 769014, 128698, 10118, 82, 34]`. Is this usage correct?

**Comment by JacoCheung** [comment]
Hi @zpcalan . Yes, you could use `slot_size_array` printed by preprocessing script. That is, all keyset files share the same slot_size_array.

**Comment by zpcalan** [comment]
I merged all 24 days' data to one data file(1TB): `day_24`, and ran `bash preprocess.sh 100 /root/HugeCTR/etc_data/day100 nvt 1 0 1`. I do so because of [this comment](https://github.com/NVIDIA-Merlin/HugeCTR/issues/397#issuecomment-1570151999), to generate `slot_size_array` and ran 24 days' data in a row with ETC.
But it failed. Error is shown below:

```
2023-06-01 04:13:11,946 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://XXX:XX after 30 s
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/distributed/utils.py", line 778, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/distributed/worker.py", line 1489, in close
    await r.close_gracefully()
  File "/usr/local/lib/python3.8/dist-packages/distributed/core.py", line 1150, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/usr/local/lib/python3.8/dist-packages/distributed/core.py", line 1371, in connect
    return await connect_attempt
  File "/usr/local/lib/python3.8/dist-packages/distributed/core.py", line 1307, in _connect
    comm = await connect(
  File "/usr/local/lib/python3.8/dist-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://XXX:XX after 30 s
2023-06-01 04:13:42,028
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/distributed/utils.py", line 778, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/distributed/worker.py", line 1441, in close
    await self.finished()
  File "/usr/local/lib/python3.8/dist-packages/distributed/core.py", line 447, in finished
    await self._event_finished.wait()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError
2023-06-01 04:13:42,084 - distributed.worker - CRITICAL - Error trying close worker in response to broken internal state. Forcibly exiting worker NOW
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/distributed/worker.py", line 180, in wrapper
    return await method(self, *args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/distributed/worker.py", line 1218, in handle_scheduler
    await self.close()
  File "/usr/local/lib/python3.8/dist-packages/distributed/utils.py", line 778, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/distributed/worker.py", line 1489, in close
    await r.close_gracefully()
  File "/usr/local/lib/python3.8/dist-packages/distributed/core.py", line 1150, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/usr/local/lib/python3.8/dist-packages/distributed/core.py", line 1371, in connect
    return await connect_attempt
  File "/usr/local/lib/python3.8/dist-packages/distributed/core.py", line 1307, in _connect
    comm = await connect(
  File "/usr/local/lib/python3.8/dist-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://XXX:XX after 30 s

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/distributed/worker.py", line 212, in _force_close
    await asyncio.wait_for(self.close(nanny=False, executor_wait=False), 30)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```
Any advice about this error? Thanks!

**Comment by JacoCheung** [comment]
Hi @zpcalan , sorry for the late response. Yes I think you cannot simply `set slot_size_array printed by any day's preprocessing script`. The slot_size_array should be large enough to hold all unique keys.

Regarding the merged file, how did you merge 0~23 into a single file?

**Comment by jershi425** [comment]
Hi @zpcalan, thank you for trying our examples. I would like to confirm the two problems you are facing. 

Firstly, you mentioned that you meet an `out of memory` problem when you launching ETC training. If I understand correctly, you have set a `slot_size_array` large enough to hold each unique key but because of the hardware limitation you got the OOM error, right? 

And secondly, for the data processing error, you encountered it when you concatenate all 24 days into one single file and try to use NVTabular to process it, right? 

Please let us know if this is the case so that we can help you. Thanks!

**Comment by zpcalan** [comment]
> Hi @zpcalan , sorry for the late response. Yes I think you cannot simply `set slot_size_array printed by any day's preprocessing script`. The slot_size_array should be large enough to hold all unique keys.
>
> Regarding the merged file, how did you merge 0~23 into a single file?
Yes, I should set slot_size_array after processing merged data file.
I merge data to one file using `cat day_0 day_1 day_2 > data` because they are just lines of texts. But if I use the script to preprocess 0~23 merged file, it failed with the above error.
So I decreased day number to 10 days and error disappeared.

**Comment by zpcalan** [comment]
> Hi @zpcalan, thank you for trying our examples. I would like to confirm the two problems you are facing.
> 
> Firstly, you mentioned that you meet an `out of memory` problem when you launching ETC training. If I understand correctly, you have set a `slot_size_array` large enough to hold each unique key but because of the hardware limitation you got the OOM error, right?

Yes, I address this issue and split large data file to multiple groups by changing the preprocessing script(and using other scripts I wrote). So that even though I set a large `slot_size_array`, each data group has unique keys which could be hold by one gpu, so the OOM error disappeared. I think this is within expectation, right?

> And secondly, for the data processing error, you encountered it when you concatenate all 24 days into one single file and try to use NVTabular to process it, right?

Yes, after I merge only 10 days data(processing more than 10 days of data still failed), this error disappeared. I also have tried to change the time out parameter in the script but it does not help.

In general, I sucessfully ran ETC to train 10 days of data after using these methods. : )
But still, some issue remains unsolved. We can keep in touch if you want other information.

**Comment by zpcalan** [comment]
About this issue, can I contribute my data processing scripts for ETC to the repo, in case that other developers run into this error?

**Comment by zehuanw** [comment]
> About this issue, can I contribute my data processing scripts for ETC to the repo, in case that other developers run into this error?

Sure, we appreciate your contribution! Once you have a PR, we will review and provide feedbacks.
