### ISSUE TITLE
[Question]Any randomness in data reader? Any randomness in Model.fit?

### ISSUE THREAD

**Issue by heroes999** [NVIDIA-Merlin/HugeCTR#398]
Does data reader shuffle the input during loading? For example, shuffle within batch or inter-batch.
Does Model.fit shuffle the input during traning, so that, for example,  sample1/sample2/sample3 from input are trained out of order(assuming batch_size=1)?

**Comment by JacoCheung** [comment]
Hi @heroes999 , which [type of data reader](https://nvidia-merlin.github.io/HugeCTR/main/api/python_interface.html#datareaderparams)you're using?

Shuffle is supported for only `DataReaderType_t.RawAsync` and there is a knob  in [AsyncParam](https://nvidia-merlin.github.io/HugeCTR/main/api/python_interface.html#asyncparam-class) to enable/disable the shuffle. The shuffle is inter batch.

**Comment by JacoCheung** [comment]
Model.fit() would not do shuffle.

**Comment by heroes999** [comment]
Get it. It seems shuffle is done by data prepare scripts. @JacoCheung
