### ISSUE TITLE
[Question]Can I build and use gpu_cache independently?

### ISSUE THREAD

**Issue by RobertLou** [NVIDIA-Merlin/HugeCTR#399]
Or I have to build the whole project?

**Comment by yingcanw** [comment]
Thanks for your question. You can get the gpu_cache library by building the whole project, or modify the [ CMakeLists.txt](https://github.com/NVIDIA-Merlin/HugeCTR/blob/main/CMakeLists.txt), such as keeping only the source and dependencies of gpu cache to get the library independently.
