### ISSUE TITLE
Build success but failed to run with CUDA 10.1

### ISSUE THREAD

**Issue by alohali** [NVIDIA-Merlin/HugeCTR#40]
Want to run hugectr on device with cuda 10.1.

Change docker config in  tools/dockerfiles/build.Dockerfile or dev.a100.Dockerfile
FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04  --> ROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

And all the thing build ok and I got hugeCTR binary files.

But then the driver seems to break down, nothing could be run. Run nvidia-smi and got
Failed to initialize NVML: Driver/library version mismatch

Try to debug I find driver broke down after   libarrow-cuda-dev install.
This line :  apt update && apt install -y libarrow-dev=0.17.1-1 libarrow-cuda-dev=0.17.1-1
It installs another libnvidia-compute-435. After installed libnvidia-compute-435, the driver could not work correctly.

Any way to solve it?

**Comment by zehuanw** [comment]
Hi @alohali , thank you for your feedback, but CUDA 10.1 is not officially supported. Could you please let us know CUDA 10.1 is still the target environment on your side and why? I'm going to close this issue, but if you still use CUDA 10.1 please reopen it we can track here again.
