### ISSUE TITLE
[Question] position bias

### ISSUE THREAD

**Issue by skunkwerk** [NVIDIA-Merlin/HugeCTR#403]
Does HugeCTR use any technique to handle position bias in the training data (clickstream data)?

thanks

**Comment by WonderingWJ** [comment]
Hi @skunkwerk . Thank you for your reaching out. Currently, we don't support it. We plan to support it in the future and have a internal issue to track it. Could you elaborate more for your user case?

**Comment by minseokl** [comment]
Closed because the issue is not active anymore.
