### ISSUE TITLE
[Question] Is there any way for hps to load an embedding table into multiple GPUs？

### ISSUE THREAD

**Issue by sparkling9809** [NVIDIA-Merlin/HugeCTR#407]
I found the lookup implementation for HPS just support to specify a GPU deviceid. So I confused is there any way for hps to load an embedding table into multiple GPUs？If there is , how can I lookup an embeding vector on multiple GPUs？

the HPS code location :    https://github.com/NVIDIA-Merlin/HugeCTR/blob/91c5c9f16060ffd7ac99867e283f157e85e8a05d/HugeCTR/include/pybind/hps_wrapper.hpp#L41

**Comment by yingcanw** [comment]
Thanks for your question. HPS initializes the embedding cache on each device through the [`deployed_devices`](https://nvidia-merlin.github.io/HugeCTR/main/hierarchical_parameter_server/hps_database_backend.html#inference-params-syntax) configured by the user (each device has an independent embedding cache and is not *shared* between devices). That is to say,  the embedding vector in the embedding cache of each device is complete, so there is no need to query an embedding vector from multiple caches.

**Comment by sparkling9809** [comment]
> 

Ok, thanks for your reply.  If the storage of GPU is not enough for hold the whole embedding table,  I should set the gpu cache percentage under 100%。 Is it right?

**Comment by yingcanw** [comment]
Currently HPS supports three embedding cache types. If your embedding table can be loaded into the GPU, it is recommended to choose _**static**_ to get the best performance. If you need to update the embedding cache dynamically online inference and the embedding table cannot be fully loaded into the GPU, you can choose **_dynamic_**. For details, please refer to the following link: [HPS configuration book](https://nvidia-merlin.github.io/HugeCTR/main/hierarchical_parameter_server/hps_database_backend.html#inference-parameters) and [HPS Arch](https://github.com/triton-inference-server/hugectr_backend/blob/main/hps_backend/docs/architecture.md#enabling-the-gpu-embedding-cache).
![image](https://github.com/NVIDIA-Merlin/HugeCTR/assets/68979322/dcee5c29-1eef-497c-8dc5-37c06ed086c4)

**Comment by sparkling9809** [comment]
> Currently HPS supports three embedding cache types. If your embedding table can be loaded into the GPU, it is recommended to choose _**static**_ to get the best performance. If you need to update the embedding cache dynamically online inference and the embedding table cannot be fully loaded into the GPU, you can choose **_dynamic_**. For details, please refer to the following link: [HPS configuration book](https://nvidia-merlin.github.io/HugeCTR/main/hierarchical_parameter_server/hps_database_backend.html#inference-parameters) and [HPS Arch](https://github.com/triton-inference-server/hugectr_backend/blob/main/hps_backend/docs/architecture.md#enabling-the-gpu-embedding-cache). ![image](https://user-images.githubusercontent.com/68979322/255592480-dcee5c29-1eef-497c-8dc5-37c06ed086c4.png)

OK， Thanks very much for your reply!
