### ISSUE TITLE
[Question] Confused about the additional element of the output of InteractionLayer

### ISSUE THREAD

**Issue by heroes999** [NVIDIA-Merlin/HugeCTR#408]
The output of InteractionLayer is of shape: batch_size  * {**num_elems** + **(num_feas + 1) * (num_feas + 2 ) / 2 - (num_feas + 1)** + _1_}, according to code or user guide.
num_elems is the dim of fc;
(num_feas+1)*(num_feas+2)/2 - (num_feas+1) stands for cross product of all embs and fc;
So what is the additional element? It seems the additional element doesn't get assigned/calculated in interaction_layer.cu/interaction_layer_test.cpp.
https://github.com/NVIDIA-Merlin/HugeCTR/blob/v4.2/test/utest/layers/interaction_layer_test.cpp#L175

Any hint will be appreciated, thanks.

**Comment by minseokl** [comment]
Hi @heroes999 are you mentioning this internal padding here? https://github.com/NVIDIA-Merlin/HugeCTR/blob/main/HugeCTR/src/layers/interaction_layer.cu#L637

**Comment by heroes999** [comment]
@minseokl I think so. 
And this is the link of introduction which tells 1 additional float output:
https://nvidia-merlin.github.io/HugeCTR/v4.2/api/hugectr_layer_book.html#interaction-layer

**Comment by minseokl** [comment]
The padding is introduced to make the output easily vectorized and TensorCore-friendly for some common use cases back then.
Yes it was mainly for __half but float has it as well to make the shape consistent regardless of if you do the mixed precision training or not.

**Comment by heroes999** [comment]
Got it. So this additional padding is always 0, right? @minseokl

**Comment by minseokl** [comment]
Yes it must be zero not to influence the result.

**Comment by heroes999** [comment]
Thanks. I'd like to close the issue
