### ISSUE TITLE
[Requirement] FS Support for Azure Blob Storage

### ISSUE THREAD

**Issue by shivamsbatra** [NVIDIA-Merlin/HugeCTR#410]
**Is your feature request related to a problem? Please describe.**
As HugeCTR currently supports AWS S3 and GCP Buckets, would be great to have a similar implementation for Azure Blob Storage as well.

**Comment by jershi425** [comment]
Hi @shivamsbatra, thank you for your feedback. At this time we don't plan to support more remote file systems. But we will let you know if we put it on our future roadmap.
