### ISSUE TITLE
[Question] Does HugeCTR support all P-series GPUs? and does it support tfserving as inference?

### ISSUE THREAD

**Issue by Shu-HowTing** [NVIDIA-Merlin/HugeCTR#411]
Does HugeCTR support all P-series GPUs? and does it support tfserving as inference?

**Comment by yingcanw** [comment]
Thanks for your question. The computing compatibility of the data center product supported by HugeCTR can be found [here](https://nvidia-merlin.github.io/HugeCTR/main/hugectr_user_guide.html#compute-capability) (CC>=6.0).

The native models trained with HugeCTR cannot be deployed directly through tfs. For the trained embedding table, it can be deployed on the tf-related inference platform through the customized  [HPS  plug-in for TensorFlow](https://nvidia-merlin.github.io/HugeCTR/main/hierarchical_parameter_server/hps_tf_user_guide.html).

**Comment by minseokl** [comment]
Hi @Shu-HowTing even if the HugeCTR supports CC>=6.0 for now, please note that we will deprecate their support in a future release.
