### ISSUE TITLE
[Question]Does HugeCtr support read data for trainning from Kafka ?

### ISSUE THREAD

**Issue by sparkling9809** [NVIDIA-Merlin/HugeCTR#413]
I want to read data from kafka to implement realtim trainning. But the dataReader in Hugectr just supports file now. is there any way to support read data for trainning from Kafka? Thanks.

**Comment by yingcanw** [comment]
Thanks for your question.  Currently, HugeCTR supports reading Parquet data, loading and saving models from/to remote file systems like [HDFS, AWS S3, and GCS](https://nvidia-merlin.github.io/HugeCTR/main/notebooks/training_and_inference_with_remote_filesystem.html).  And we only support Kafka in inference to support online update of incremental models to [HPS](https://nvidia-merlin.github.io/HugeCTR/main/hierarchical_parameter_server/hps_database_backend.html#update-source-configuration). @jershi425 Please add your comments.

**Comment by sparkling9809** [comment]
OK， thanks !
