### ISSUE TITLE
[FEA] Make optional the number of files in Norm Dataset File List 

### ISSUE THREAD

**Issue by miguelusque** [NVIDIA-Merlin/HugeCTR#42]
Hi!

I am not sure if starting the norm dataset file with the number of files in the list is the best option.

IMO, that value should not be needed, because it might be easily calculated by the parser. It might also be a source of future errors if the parser doesn't double-check that the number specified corresponds to the number of files detailed in the norm dataset file.

Therefore, I would suggest to make that value optional.

https://github.com/NVIDIA/HugeCTR/blob/master/docs/hugectr_user_guide.md#file-list

Hope it helps!

**Comment by JacoCheung** [comment]
Hi @miguelusque , thanks for your advice. I believe we're setting the value for debugging usage. But yes, the first line--number of files could be optional. We'll adopt your suggestion and of cource more convenient ways specifying the dataset files is already planned. We'll announce the new features once it's available.
