### ISSUE TITLE
[Question] nv_gpu_cache compiling problem

### ISSUE THREAD

**Issue by RobertLou** [NVIDIA-Merlin/HugeCTR#428]
I'm trying to test **nv_gpu_cache** with **cache_op_sol_test**, but encounter strange compiling problems:
1.Changes made in **nv_gpu_cache.cu** don't seem to affect the results. Even if I add code like _printf()_ or _std::cout_, the console output doesn't include my new output. Additionally, when I delete functions like _init_cache()_, it appears that they are still being executed when profiling with **nvprof**.
2. When I intentionally introduce syntax errors in **nv_gpu_cache.cu**, the compiler does show the errors, indicating that it is compiling the file.
My compile code is shown below:
`cmake -DCMAKE_BUILD_TYPE=Release -DSM=75 -DENABLE_INFERENCE=ON .. `
`make -j cache_op_sol_test`
My running commands is shown below：
`./bin/cache_op_sol_test 4096 512 128 128 2 1 0`
Environment:
Tesla T4 with GPU docker nvcr.io/nvidia/merlin/merlin-hugectr:23.08

**Comment by yingcanw** [comment]
@RobertLou If you are using ngc docker image, then we have pre-installed all libraries of  V23.08 to the default path(`/usr/local/hugectr`), and add to `LD_LIBRARY_PATH`.  Therefore, if you need to do customized development, please `make install `the new library or delete the default installation library and re-specify your library path.
