### ISSUE TITLE
[Question] What is the difference between HugeCTR/embedding and HugeCTR/src/embeddings?

### ISSUE THREAD

**Issue by Orca-bit** [NVIDIA-Merlin/HugeCTR#459]
This template is for generic questions that a user may have in using HugeCTR.

**Note**: Before filing an issue, you may want to check out [our compiled Q&A list](https://github.com/NVIDIA/HugeCTR/blob/master/docs/QAList.md) first.

**Comment by shijieliu** [comment]
Hi @Orca-bit thanks for your interest for HugeCTR!

`HugeCTR/src/embeddings` and `HugeCTR/embedding` are two seperate embedding implementations. Compared with `HugeCTR/src/embeddings`, `HugeCTR/embedding` provides more flexible API for user to configure sharding. 

To be more specific, `HugeCTR/src/embeddings` only support localized or distributed embedding but in `HugeCTR/embedding` user can specify the table placement for each GPU. If you are interested in the detail, you can refer to our paper published in RecSys 2024 entitled `Embedding Optimization for Training Large-scale Deep Learning Recommendation Systems with EMBark`.

Our goal is to improve `HugeCTR/embedding` and will deprecate `HugeCTR/src/embeddings` in the future.
