### ISSUE TITLE
[FEA] Support cudf 0.16

### ISSUE THREAD

**Issue by albert17** [NVIDIA-Merlin/HugeCTR#49]
Currently HugeCTR does not support cudf 0.16. It keeps throwing the following error.

```
/home/rapids/hugectr/HugeCTR/include/data_readers/parquet_data_reader_worker.hpp:29:10: fatal error: cudf/io/functions.hpp: No such file or directory
 #include <cudf/io/functions.hpp>
```

cudf 0.16 has refactored some code, and the functions.hpp does not exist anymore. Includes in HugeCTR have to be updated.

**Comment by zehuanw** [comment]
Could you please elaborate why you need cudf 0.16? or how important this issue to you?

**Comment by zehuanw** [comment]
Copy to Gitlab for easier tracking in v2.3 integration

**Comment by bashimao** [comment]
https://github.com/NVIDIA-Merlin/HugeCTR/issues/253
