### ISSUE TITLE
[ QUESTION ] training without eval set

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA-Merlin/HugeCTR#52]
Is there a way to run training without having a validation set? Whenever I don't have anything for source_eval I got an file_empty kind of error. 

On top of that, HugeCTR really needs to work on error messages, I had to trace the code to see what is happening.

**Comment by minseokl** [comment]
Hi Ethem, unfortunately it is not allowed not to specify `source_eval`.  A workaround it to set `source_eval` as the same as `source`, and set `eval_interval` to an extremely large number.

**Comment by zehuanw** [comment]
Hi @ethem-kinginthenorth , I would like to close this issue. @minseokl 's reply doesn't solve your problem, please reopen it. Thanks!
