### ISSUE TITLE
dump_to_tf throwing memory error

### ISSUE THREAD

**Issue by ketanchothani13** [NVIDIA-Merlin/HugeCTR#53]
I followed instructions given in /hugectr/tutorials/dump_to_tf/ReadMe. 
But when running "python3 main.py \
../../samples/dcn/dcn_bin.json \
../../samples/dcn/train/0.data \
../../samples/dcn/_dense_9999.model \
../../samples/dcn/0_sparse_9999.model", I am getting memory exception. Please refer attached screenshot for actual error.

Note: I have used nvtabular with binary format to preprocess and train with hugectr. Hence config file used in above command
![dump_to_tf_error](https://user-images.githubusercontent.com/6790121/97167281-8ea62900-17ac-11eb-97bc-518d5f171baa.png)
![free-memory-in-gb](https://user-images.githubusercontent.com/6790121/97167342-a2518f80-17ac-11eb-8e1d-ab2269113fca.png)

 is dcn_bin.json.

**Comment by KingsleyLiu-NV** [comment]
`read_a_sample_for_dcn` can only read the Norm Form data of HugeCTR. If you use data of other formats, you need to write another function to read a sample.
